### ISSUE TITLE
add code to install the vagrant-proxyconf plugin

### ISSUE THREAD

**Issue by craigmcb** [oracle/vagrant-projects#172]
Perhaps you could add this to Vagrantfile..

unless Vagrant.has_plugin?("vagrant-proxyconf")
 puts 'Installing vagrant-proxyconf Plugin...'
 system('vagrant plugin install vagrant-proxyconf')
end

**Comment by Djelibeybi** [comment]
@craigmcb is being somewhat gnomic here. The Vagrantfile in question is the OLCNE one.

**Comment by AmedeeBulle** [comment]
I am not in favor of blindly installing third party plugins that are not strictly necessary for most users.

I'd rather improve the instruction for user behind proxies.

Alternatively we could configure proxies without using this plugin -- in particular for this box as it doesn't work for `podman` / `cri-o` anyway...

**Comment by Djelibeybi** [comment]
Sure, that makes sense. In which case, this should probably be documented in the  [contribution guide](https://github.com/oracle/vagrant-boxes/blob/master/CONTRIBUTING.md) so that other potential contributors are aware of how to handle plugin requirements.

**Comment by AmedeeBulle** [comment]
README files have been updated in various PRs (#257, #271, ...)

Can we close this issue?
