### ISSUE TITLE
OLCNE default resources are insufficient for Istio

### ISSUE THREAD

**Issue by rafabene** [oracle/vagrant-projects#237]
OLCNE with 2 worker nodes is not enough to run all pods of Istio. When observing the pods, some of them are in the `Pending` state and the cause is:

>Warning  FailedScheduling  2m11s (x2 over 2m11s)  default-scheduler  0/3 nodes are available: 1 node(s) had taints that the pod didn't tolerate, 2 Insufficient memory.
  Warning  FailedScheduling  55s (x2 over 55s)      default-scheduler  0/3 nodes are available: 1 Insufficient cpu, 1 Insufficient memory, 1 node(s) had taints that the pod didn't tolerate.

Some possible solutions:
- Set the minimum number of Worker Nodes as 3 if ISTIO variable is true
- Document the minimum number of worker node for Istio
- Remove the taint of master
- Increase the vCPUs to 3 by default

**Comment by Djelibeybi** [comment]
I'm running Istio with 2 worker nodes. The bump to 3GB of RAM and 2 vCPUs should've covered the requirements. Let me see if I can reproduce this locally.

Note that we're not going to untaint the master, but we may increase the vCPUs (if necessary). I don't want to increase the minimum worker node count unless we really have to.

**Comment by rafabene** [comment]
Another possible solution would be running a single replica for each pod in the Istio control plane. I noticed that there are two replicas for each one of them. Is that something possible to do during the module installation?

**Comment by Djelibeybi** [comment]
We need at least two replicas for the module in order to support a zero-impact upgrade process. I'll check what (if any) options are available when we create the module, but I suspect this isn't (currently) possible).

**Comment by Djelibeybi** [comment]
I've closed the PR that increases the resources. We may need to look at modiying the Istio configuration prior to deployment to lower the resource requirements.

**Comment by rafabene** [comment]
Maybe OCLNE should allow the user to choose an Istio [configuration profile](https://istio.io/docs/setup/additional-setup/config-profiles/)

**Comment by Djelibeybi** [comment]
That would make a good ER for OLCNE, yes. I'll open it internally.

**Comment by AmedeeBulle** [comment]
Do we need to keep this issue open?

There isn't anything directly actionable for this project at this point in time...

**Comment by Djelibeybi** [comment]
No, this can be closed. There is an internal enhancement request to track this.
