### ISSUE TITLE
Stderr: VBoxManage.exe: error: Cannot change type for medium vagrant-boxes\OracleRAC\asm_disk2.vdi' to 'Shareable' since it is a dynamic medium storage unit

### ISSUE THREAD

**Issue by faguirre154** [oracle/vagrant-projects#256]

**Comment by faguirre154** [comment]
C:\Users\5520\Downloads\GitHub repositories\vagrant-boxes\OracleRAC>vagrant up

│▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│
 Oracle RAC (Real Application Cluster) Vagrant box for KVM/libVirt or VirtualBox
 Copyright (c) 1982-2020 Oracle and/or its affiliates
----------------------------------------------------------------------------------
 Author: Ruggero Citton <ruggero.citton@oracle.com>
         RAC Pack, Cloud Innovation and Solution Engineering Team
│▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│


--------------------
Detected virtualbox
--------------------
ERROR: gi_software does not exist

C:\Users\5520\Downloads\GitHub repositories\vagrant-boxes\OracleRAC>vagrant up

│▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│
 Oracle RAC (Real Application Cluster) Vagrant box for KVM/libVirt or VirtualBox
 Copyright (c) 1982-2020 Oracle and/or its affiliates
----------------------------------------------------------------------------------
 Author: Ruggero Citton <ruggero.citton@oracle.com>
         RAC Pack, Cloud Innovation and Solution Engineering Team
│▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│


--------------------
Detected virtualbox
--------------------
Installing vagrant-reload Plugin...
Installing the 'vagrant-reload' plugin. This can take a few minutes...
Fetching vagrant-reload-0.0.1.gem
Installed the plugin 'vagrant-reload (0.0.1)'!
Installing vagrant-proxyconf Plugin...
Installing the 'vagrant-proxyconf' plugin. This can take a few minutes...
Fetching vagrant-proxyconf-2.0.7.gem
Installed the plugin 'vagrant-proxyconf (2.0.7)'!
Bringing machine 'node2' up with 'virtualbox' provider...
Bringing machine 'node1' up with 'virtualbox' provider...
==> node2: Box 'oraclelinux/7' could not be found. Attempting to find and install...
    node2: Box Provider: virtualbox
    node2: Box Version: >= 0
==> node2: Loading metadata for box 'https://oracle.github.io/vagrant-boxes/boxes/oraclelinux/7.json'
    node2: URL: https://oracle.github.io/vagrant-boxes/boxes/oraclelinux/7.json
==> node2: Adding box 'oraclelinux/7' (v7.8.128) for provider: virtualbox
    node2: Downloading: https://yum.oracle.com/boxes/oraclelinux/ol7/ol7u8-virtualbox-b128.box
    node2:
    node2: Calculating and comparing box checksum...
==> node2: Successfully added box 'oraclelinux/7' (v7.8.128) for 'virtualbox'!
==> node2: Importing base box 'oraclelinux/7'...
==> node2: Matching MAC address for NAT networking...
==> node2: Setting the name of the VM: vgtol7-rac-node2
Vagrant is currently configured to create VirtualBox synced folders with
the `SharedFoldersEnableSymlinksCreate` option enabled. If the Vagrant
guest is not trusted, you may want to disable this option. For more
information on this option, please refer to the VirtualBox manual:

  https://www.virtualbox.org/manual/ch04.html#sharedfolders

This option can be disabled globally with an environment variable:

  VAGRANT_DISABLE_VBOXSYMLINKCREATE=1

or on a per folder basis within the Vagrantfile:

  config.vm.synced_folder '/host/path', '/guest/path', SharedFoldersEnableSymlinksCreate: false
==> node2: Clearing any previously set network interfaces...
==> node2: Preparing network interfaces based on configuration...
    node2: Adapter 1: nat
    node2: Adapter 2: hostonly
    node2: Adapter 3: intnet
==> node2: Forwarding ports...
    node2: 22 (guest) => 2222 (host) (adapter 1)
==> node2: Running 'pre-boot' VM customizations...
A customization command failed:

["storageattach", :id, "--storagectl", "SATA Controller", "--port", 5, "--device", 0, "--type", "hdd", "--medium", "./asm_disk2.vdi", "--mtype", "shareable", "--nonrotational", "on"]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["storageattach", "c22e5262-beaa-4947-888a-ebe5af0e2e2a", "--storagectl", "SATA Controller", "--port", "5", "--device", "0", "--type", "hdd", "--medium", "./asm_disk2.vdi", "--mtype", "shareable", "--nonrotational", "on"]

Stderr: VBoxManage.exe: error: Cannot change type for medium 'C:\Users\5520\Downloads\GitHub repositories\vagrant-boxes\OracleRAC\asm_disk2.vdi' to 'Shareable' since it is a dynamic medium storage unit
VBoxManage.exe: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MediumWrap, interface IMedium, callee IUnknown
VBoxManage.exe: error: Context: "COMSETTER(Type)(enmMediumType)" at line 708 of file VBoxManageStorageController.cpp
VBoxManage.exe: error: Failed to set the medium type
>

Please fix this customization and try again.

C:\Users\5520\Downloads\GitHub repositories\vagrant-boxes\OracleRAC>

**Comment by rcitton** [comment]
- "ERROR: gi_software does not exist" --> is not an error, you are not providing the required GI binary
- The "VBoxManage.exe: error:" seems to be a VBox issue. Which OS, Vbox and Vagrant version are you using?

**Comment by faguirre154** [comment]
My fault, I edited my previous comment, below last part of that error trying to install OracleRAC vagrant-box and I also included "dir" info of OracleRAC directores:

Stderr: VBoxManage.exe: error: Cannot change type for medium 'C:\Users\5520\Downloads\GitHub repositories\vagrant-boxes\OracleRAC\asm_disk2.vdi' to 'Shareable' since it is a dynamic medium storage unit
VBoxManage.exe: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MediumWrap, interface IMedium, callee IUnknown
VBoxManage.exe: error: Context: "COMSETTER(Type)(enmMediumType)" at line 708 of file VBoxManageStorageController.cpp
VBoxManage.exe: error: Failed to set the medium type
--------------------------------------------------------------------------------------------------------
C:\Users\5520\Downloads\GitHub repositories\vagrant-boxes>dir
 El volumen de la unidad C no tiene etiqueta.
 El número de serie del volumen es: 6AD2-6A81

 Directorio de C:\Users\5520\Downloads\GitHub repositories\vagrant-boxes

04/06/2020  11:35 p. m.    <DIR>          .
04/06/2020  11:35 p. m.    <DIR>          ..
04/06/2020  11:35 p. m.                40 .gitignore
04/06/2020  11:35 p. m.               313 CODEOWNERS
04/06/2020  11:35 p. m.    <DIR>          ContainerRegistry
04/06/2020  11:35 p. m.             1,750 CONTRIBUTING.md
04/06/2020  11:35 p. m.    <DIR>          DockerEngine
04/06/2020  11:35 p. m.    <DIR>          Kubernetes
04/06/2020  11:35 p. m.    <DIR>          LAMP
04/06/2020  11:35 p. m.             1,890 LICENSE
04/06/2020  11:35 p. m.    <DIR>          OLCNE
04/06/2020  11:35 p. m.    <DIR>          OracleAPEX
07/06/2020  06:32 p. m.    <DIR>          OracleDatabase
08/06/2020  11:07 a. m.    <DIR>          OracleDG
04/06/2020  11:35 p. m.    <DIR>          OracleFPP
04/06/2020  11:35 p. m.    <DIR>          OracleLinux
08/06/2020  11:49 a. m.    <DIR>          OracleRAC
04/06/2020  11:35 p. m.               568 README.md
               5 archivos          4,561 bytes
              13 dirs  159,871,668,224 bytes libres

C:\Users\5520\Downloads\GitHub repositories\vagrant-boxes>cd OracleRAC

C:\Users\5520\Downloads\GitHub repositories\vagrant-boxes\OracleRAC>dir
 El volumen de la unidad C no tiene etiqueta.
 El número de serie del volumen es: 6AD2-6A81

 Directorio de C:\Users\5520\Downloads\GitHub repositories\vagrant-boxes\OracleRAC

08/06/2020  11:49 a. m.    <DIR>          .
08/06/2020  11:49 a. m.    <DIR>          ..
04/06/2020  11:35 p. m.                21 .gitattributes
04/06/2020  11:35 p. m.                59 .gitignore
05/06/2020  09:34 p. m.    <DIR>          .vagrant
05/06/2020  08:19 p. m.    21,476,933,632 asm_disk2.vdi
04/06/2020  11:35 p. m.    <DIR>          config
04/06/2020  11:35 p. m.    <DIR>          images
04/06/2020  11:35 p. m.             1,896 LICENSE.txt
07/06/2020  06:32 p. m.    <DIR>          ORCL_software
04/06/2020  11:35 p. m.            12,033 README.md
04/06/2020  11:35 p. m.    <DIR>          scripts
04/06/2020  11:35 p. m.             5,449 THIRD_PARTY_LICENSES.txt
04/06/2020  11:35 p. m.    <DIR>          userscripts
04/06/2020  11:35 p. m.            24,415 Vagrantfile
               7 archivos 21,476,977,505 bytes
               8 dirs  159,871,664,128 bytes libres

C:\Users\5520\Downloads\GitHub repositories\vagrant-boxes\OracleRAC>cd ORCL_software

C:\Users\5520\Downloads\GitHub repositories\vagrant-boxes\OracleRAC\ORCL_software>dir
 El volumen de la unidad C no tiene etiqueta.
 El número de serie del volumen es: 6AD2-6A81

 Directorio de C:\Users\5520\Downloads\GitHub repositories\vagrant-boxes\OracleRAC\ORCL_software

07/06/2020  06:32 p. m.    <DIR>          .
07/06/2020  06:32 p. m.    <DIR>          ..
06/06/2020  12:25 a. m.             2,759 advanced-visualizations-in-splunk.ics
06/06/2020  12:20 a. m.             3,415 architecture-for-continuous-delivery.ics
06/06/2020  12:22 a. m.             2,842 aws-administration-essentials-security-identity-and-access-management.ics
06/06/2020  12:09 a. m.             5,653 aws-certified-sysops-administrator-associate-crash-course.ics
06/06/2020  12:14 a. m.             1,743 aws-technical-essentials.ics
06/06/2020  12:17 a. m.             1,964 azure-administrator-certification-az-104-crash-course.ics
06/06/2020  12:16 a. m.             2,875 cybersecurity-offensive-and-defensive-techniques-in-3-hours.ics
06/06/2020  12:11 a. m.             4,535 getting-started-with-amazon-web-services-aws.ics
06/06/2020  12:31 a. m.             2,046 implementing-infrastructure-as-code.ics
06/06/2020  12:30 a. m.             1,449 java-essentials-start-building-your-own-java-applications.ics
05/06/2020  07:32 p. m.     3,059,705,302 LINUX.X64_193000_db_home.zip
05/06/2020  07:56 p. m.     2,889,184,573 LINUX.X64_193000_grid_home.zip
07/06/2020  04:12 p. m.             3,535 meet-the-expert-tim-oreilly-on-preparing-for-the-post-covid-future.ics
06/06/2020  12:33 a. m.             2,760 microsoft-power-bi-first-steps.ics
04/06/2020  11:35 p. m.               204 put_Oracle-software_here.txt
06/06/2020  12:28 a. m.             1,925 spark-30-first-steps.ics
06/06/2020  12:27 a. m.             2,780 terraform-getting-started.ics
06/06/2020  12:20 a. m.             2,421 up-and-running-with-kubernetes-a-practical-approach.ics
06/06/2020  12:38 a. m.             2,985 writing-cool-bash-shell-scripts-in-3-hours.ics
              19 archivos  5,948,935,766 bytes
               2 dirs  159,871,655,936 bytes libres

**Comment by faguirre154** [comment]
Could you please review my previous comment?

**Comment by rcitton** [comment]
As said:
ERROR: gi_software does not exist" --> is not an error, you are not providing the required GI binary
you must provide the binaries.
Please see readme:
--> Getting started
--> 3. Download Grid Infrastructure and Database binary from OTN into ./ORCL_software folder (*)
--------------
About VirtualBox error:
.
VBoxManage.exe: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MediumWrap, interface IMedium, callee IUnknown
VBoxManage.exe: error: Context: "COMSETTER(Type)(enmMediumType)" at line 708 of file VBoxManageStorageController.cpp
VBoxManage.exe: error: Failed to set the medium type
.
seems to be a VBox issue. 
Which OS, Vbox and Vagrant version are you using?

**Comment by rcitton** [comment]
As said:
ERROR: gi_software does not exist" --> is not an error, you are not providing the required GI binary
you must provide the binaries.
Please see readme:
--> Getting started
--> 3. Download Grid Infrastructure and Database binary from OTN into ./ORCL_software folder (*)
--------------
About VirtualBox error:
.
VBoxManage.exe: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MediumWrap, interface IMedium, callee IUnknown
VBoxManage.exe: error: Context: "COMSETTER(Type)(enmMediumType)" at line 708 of file VBoxManageStorageController.cpp
VBoxManage.exe: error: Failed to set the medium type
.
seems to be a VBox issue. 
Which OS, Vbox and Vagrant version are you using?

**Comment by faguirre154** [comment]
Sorry to insist but database & grid software was placed in that path (above comments):

Directorio de C:\Users\5520\Downloads\GitHub repositories\vagrant-boxes\OracleRAC\ORCL_software
........
05/06/2020  07:32 p. m.     3,059,705,302 LINUX.X64_193000_db_home.zip
05/06/2020  07:56 p. m.     2,889,184,573 LINUX.X64_193000_grid_home.zip
.......

**Comment by rcitton** [comment]
Im sorry Francisco Im confuse.
Are you getting "ERROR: gi_software does not exist"?
or the error is about "VBoxManage.exe" ?
or both?

**Comment by faguirre154** [comment]
Windows 10 Pro, Vbox Version 6.1.8 r137981 (Qt5.6.2), vagrant 2.2.9

C:\Users\5520\Downloads\GitHub repositories\vagrant-boxes\OracleDG>VBoxManage -version
6.1.8r137981
C:\Users\5520\Downloads\GitHub repositories\vagrant-boxes\OracleDG>vagrant version
│▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│
 Oracle DG (Database Dataguard) Vagrant box for KVM/libVirt or VirtualBox
 Copyright (c) 1982-2020 Oracle and/or its affiliates
--------------------------------------------------------------------------
 Author: Ruggero Citton <ruggero.citton@oracle.com>
         RAC Pack, Cloud Innovation and Solution Engineering Team
│▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│
--------------------
Detected virtualbox
--------------------
getting Proxy Configuration from Host...
Installed Version: 2.2.9
Latest Version: 2.2.9

**Comment by rcitton** [comment]
Are you getting "ERROR: gi_software does not exist"?
or the error is about "VBoxManage.exe" ?
or both?

**Comment by faguirre154** [comment]
In VBoxManage:
VBoxManage.exe: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MediumWrap, interface IMedium, callee IUnknown
VBoxManage.exe: error: Context: "COMSETTER(Type)(enmMediumType)" at line 708 of file VBoxManageStorageController.cpp
VBoxManage.exe: error: Failed to set the medium type

**Comment by AmedeeBulle** [comment]
A couple of things...

- Windows 10: ensure Hyper-V is disabled, it does not play well with VirtualBox. You can disable HyperV with `bcdedit /set hypervisorlaunchtype off` and reboot the system.
- Check that you have a clean environment before (re-)trying. That is:
  - run `vagrant destroy -f`
  - no leftover disk from previous attempts -- run `vboxmanage list hdds` to verify

Side note: you can use triple backticks (\`\`\`) around console output to enhance readability of your posts.

**Comment by faguirre154** [comment]
Thanks Philippe for your comments. I destroyed my previous environments and I started all over again but this time I did not have enough space (80 Gb free space disk) for my Oracle RAC vagrant environment. In the meantime I've already successfully installed Oracle 12.2c and OracleDG environments. From my side I close this issue and thanks again for your help.
