### ISSUE TITLE
Oracle Linux 7 vagrant box is not available

### ISSUE THREAD

**Issue by agntdv** [oracle/vagrant-projects#261]
when spinning up vagrant with Oracle 19.0.3, it returns 404 as https://oracle.github.io/vagrant-boxes/boxes/oraclelinux/7.json is not available, in fact, none of Json is available from the http://yum.oracle.com/boxes/

````
$ vagrant up
getting Proxy Configuration from Host...
Bringing machine 'oracle-19c-vagrant' up with 'virtualbox' provider...
==> oracle-19c-vagrant: Box 'oraclelinux/7' could not be found. Attempting to find and install...
    oracle-19c-vagrant: Box Provider: virtualbox
    oracle-19c-vagrant: Box Version: >= 0
==> oracle-19c-vagrant: Box file was not detected as metadata. Adding it directly...
==> oracle-19c-vagrant: Adding box 'oraclelinux/7' (v0) for provider: virtualbox
    oracle-19c-vagrant: Downloading: https://oracle.github.io/vagrant-boxes/boxes/oraclelinux/7.json
    oracle-19c-vagrant:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404
````

**Comment by Djelibeybi** [comment]
This is due to the change from `vagrant-boxes` to `vagrant-projects`. I guess GitHub's redirect doesn't follow for GH Pages.

**Comment by PaulNeumann** [comment]
@Djelibeybi I was just getting ready to open an issue to that effect. This affects all of the Vagrantfiles in this repository, as well as the links and static text on the [https://yum.oracle.com/boxes](https://yum.oracle.com/boxes) page.

@agntdv as a temporary workaround, you can change line 20 of the `Vagrantfile` from 

```ruby
BOX_URL = "https://oracle.github.io/vagrant-boxes/boxes"
```

to

```ruby
BOX_URL = "https://oracle.github.io/vagrant-projects/boxes"
```

This will allow the build to work.

**Comment by Djelibeybi** [comment]
Yep, I've just opened a PR to fix this.

**Comment by Djelibeybi** [comment]
This has now been fixed. Sorry for the inconvenience!
