### ISSUE TITLE
OracleDatabase - Error: Package does not match intended download

### ISSUE THREAD

**Issue by jsfelix** [oracle/vagrant-projects#267]
This error occurs when I tried wake up a oracle database 12c server, following these steps:

`git clone https://github.com/oracle/vagrant-boxes`
`cd vagrant-boxex/OracleDatabase/12.2.0.1/`
(after download oracledatbase installer)
`vagrant up`

Error:

```
oracle-12201-vagrant: http://yum.oracle.com/repo/OracleLinux/OL7/UEKR5/x86_64/getPackage/kernel-uek-devel-4.14.35-1902.303.4.1.el7uek.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=ol7_UEKR5 clean metadata

    oracle-12201-vagrant: Trying other mirror.
    oracle-12201-vagrant:
    oracle-12201-vagrant:
    oracle-12201-vagrant: Error downloading packages:
    oracle-12201-vagrant:   kernel-uek-devel-4.14.35-1902.303.4.1.el7uek.x86_64: [Errno 256] No more mirrors to try.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

I tried to clear the metadata and the yum cache, but the problem still occurs.

**Comment by gvenzl** [comment]
@scoter-oracle, @totalamateurhour, any clues as to why the yum mirror seems to have an issue with the package?

**Comment by PaulNeumann** [comment]
@jsfelix If you're using a Windows host, this kind of error can happen when Hyper-V is enabled. VirtualBox has experimental support for Hyper-V, but they aren't completely compatible.

**Comment by jsfelix** [comment]
After disable Hyper-V on Windows, I removed the VM and tried `vagrant up`, without success. I think it's a problem with Akamai CDN, because it also occurs with ISO images from yum.oracle.com

**Comment by jsfelix** [comment]
Result of `sudo yum update`:

```
(9/16): ol7_latest/x86_64/updateinfo                                     | 2.8 MB  00:00:00
ol7_UEKR5/x86_64/primary_db    FAILED                                          MB  --:--:-- ETA http://yum.oracle.com/repo/OracleLinux/OL7/UEKR5/x86_64/repodata/388a3f43f38517fd576995206cf1dd59896ee333-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
Trying other mirror.
```

**Comment by totalamateurhour** [comment]
> because it also occurs with ISO images from yum.oracle.com

So if you download an Oracle Linux ISO from yum.oracle.com, the published checksum doesn’t match the checksum of the downloaded ISO? That’s not something I’ve seen reported before. Those ISO files never change, so whatever is in Akamai’s cache should be correct. 

In this case, are you downloading the ISO from the Windows host or from within a guest also?

**Comment by jsfelix** [comment]
No, I had the same problema when I run yum update.

Em seg, 15 de jun de 2020 14:09, Sergio Leunissen <notifications@github.com>
escreveu:

**Comment by jsfelix** [comment]
I also disabled Hipervisor Windows Platform and Virtual Machine Platform and now it's working.

**Comment by PaulNeumann** [comment]
@jsfelix Excellent! I'm glad it's working.

There are several Windows features that use Hyper-V, including Application Guard, Credential Guard, Device Guard, Containers, Virtual Machine Platform, Windows Hypervisor Platform, Windows Sandbox, and Windows Subsystem for Linux (WSL2 only; WSL1 does *not* use Hyper-V). If any of these features are enabled, it can cause problems for VirtualBox.
