### ISSUE TITLE
Provide slim base boxes with a single disk

### ISSUE THREAD

**Issue by webfrasse** [oracle/vagrant-projects#278]
Virtualbox allows you to export a VM directly to your OCI tenancy. One limitation when importing a custom image to OCI is that the VM can only have one disk. Current Vagrant boxes have two images and while the export to OCI proceeds without errors the OCI instance is not functional. You can not connect to it even though an IP is assigned.

The very simple workaround is to simply delete the second disk in the Virtualbox Manager for the Vagrant VM. 

Quick solution could be to document this work around but many use cases for simpler boxes does not require the second disk  hence the idea for a slim base box with a single disk.

**Comment by totalamateurhour** [comment]
Fixed in latest release of boxes.
