### ISSUE TITLE
APEX project - Support ORDS 20.2

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-projects#281]
ORDS 20.2 has been released. The `ords.sh` script for the APEX project doesn't find the ORDS 20.2 installer zip file, because it looks for files matching `ords[_-]1*.*.zip`.

Replacing line 34 of `ords.sh`, which is currently:

```bash
ORDS_INSTALL=`ls /vagrant/ords[_-]1*.*.zip |tail -1`
```

with the following:

```bash
ORDS_INSTALL=$(find /vagrant -maxdepth 1 -name "ords[_-]*.*.zip" -type f | tail -1)

if [[ -z ${ORDS_INSTALL} || ! -r "${ORDS_INSTALL}" ]]; then
  echo 'INSTALLER: Could not find ORDS installer file. Exiting.'
  exit 1
fi
```

allows the script to work with ORDS 20.2 and above, as well as earlier versions. It also eliminates two ShellCheck warnings. This is nearly identical to the change made in #224 to the `apex.sh` script to support APEX 20.1.

I've verified that the project builds and runs correctly with this change. If you agree that this is a legitimate issue, and that the suggested approach is correct, I'd be happy to submit a PR.

**Comment by scoter-oracle** [comment]
hi Paul,

thanks so much for your support on this.
Feel free to submit a PR, thanks, again.
