### ISSUE TITLE
Top level README suggestion - Windows/Hyper-V

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-projects#285]
There have been a few issues (#267, #240, #222, #216) with these projects related to Hyper-V on Windows hosts. Would it be helpful to add a note in the "Known issues" section of the top level README about this?  Perhaps something like:

### Hyper-V on Windows hosts

The projects in this repository are unlikely to work correctly on Windows hosts with Hyper-V enabled.

Windows features that enable Hyper-V include Application Guard, Containers, Credential Guard, Device Guard, Hyper-V, Virtual Machine Platform, Windows Hypervisor Platform, Windows Sandbox, and Windows Subsystem for Linux (WSL2 only; WSL1 does _not_ use Hyper-V). If you encounter problems with the projects on a Windows host, please try disabling these features.

**Comment by igranat** [comment]
Yes, please  add a note to Known issues - it took me a while to find this post.

**Comment by totalamateurhour** [comment]
@PaulNeumann please submit a PR. Makes sense to me.

**Comment by PaulNeumann** [comment]
@totalamateurhour PR submitted. Thanks!
