### ISSUE TITLE
FPP deployment suggestion: Provision host2 with a 12c database to allow finer upgrade scenarios

### ISSUE THREAD

**Issue by brokedba** [oracle/vagrant-projects#289]
Hi there,

I am opening this issue as an enhancement suggestion regarding your Oracle FPP build. I have run it lately and I thought that shipping the host2 with a 12c database would really be valuable for users who seek to practice on 12c to 18/19 migration as most of the customers are looking to achieve that transitions lately.

 

- I started to tweak the vagrantfile and the yaml file for starters but it'll also need modifications in the setup script.    

 

- The idea could be adding a boolean in the yaml file called db_deploy so the user can choose to installed or not the DB and also  define some variables. Guessing another disk (u02) will be required to store the data as weel.

The host2 yaml vars coud look like this 

![image](https://user-images.githubusercontent.com/29458929/89244819-7a032c00-d5d5-11ea-9977-2173f4bdf34e.png)

**Comment by brokedba** [comment]
Made some progress . I modified the scripts so an additional disk would be added to map /u02 in host2 along with a 12.1.0.2 db install. I took a portion of the setup scripts already  hosted in this repo and adapted it to pick the variables defined in the vagrantfile (vagrant-projects/OracleDatabase/12.1.0.2/).
- So far I bumped into a little error below while running the dbca but it could be due to some missing  rpm (not sure if the 18c preinstall_rpm would colide with the one for 12c )  
`host2: UnsatisfiedLinkError exception loading native library: njni12
    host2: java.lang.UnsatisfiedLinkError: /u01/app/oracle/product/12.1.0.2/dbhome_1/lib/libnjni12.so: /u01/app/oracle/product/12.1.0.2/dbhome_1/lib/libclnt`    
will share more if it works.

**Comment by brokedba** [comment]
I fixed the installer error and I now have the build ship the host2 with a fresh install of 12.2.0.2 Database.
I will update my fork and share the link if you guys find it useful. 

- my question is : once we have a running  database home in the FPP client what rhpctl import image command should we hit to create an image in the FPP server ??? . 
I gave it a shot but it didn't go well :p . Any idea?
```
 [grid@fpp-Server ~]$ rhpctl import image -image db_12102 -imagetype ORACLEDBSOFTWARE -path /u01/app/oracle/product/12.1.0.2/dbhome_1 -targetnode fpp-Client -root
Enter user "root" password:
fpp-Server.evilcorp.com: Adding storage for image ...
fpp-Server.evilcorp.com: Creating a new ACFS file system for image "db_12102" ...
fpp-Server.evilcorp.com: Creating export file system ...
fpp-Server.evilcorp.com: Starting export file system...
fpp-Server.evilcorp.com: Mounting file system...
PRGO-1257 : failed to import image "db_12102"
PRGO-1257 : failed to import image "db_12102"
PRCZ-2105 : failed to execute command "/bin/mount" as user "root" using root credentials within 300 seconds on nodes "fpp-Client"
PRCZ-2103 : Failed to execute command "/bin/mount" on node "fpp-Client" as user "root". Detailed error:mount.nfs: Connection refused 
```
Sorry but the [official  documentation on RHP](https://docs.oracle.com/en/database/oracle/oracle-database/19/cwadd/rapid-home-provisioning-and-server-control-command-reference.html#GUID-5282B39C-4D95-4205-A180-ED4D874E2540) doesn't help a lot when it gets specific.

**Comment by rcitton** [comment]
Hi @brokedba , the scope of FPP@Vagrant with host2 created, its to offer the possibility to make practice with FPP. The practice is starting (as documented in the readme) with the import of GI/RDBMS image, the shipping of RDBMS image to the target (host2) and latest the DB creation from FPP Server to the target (host2). Of course an user could get the 12c binaries, install them into the server(or on host2 too, like you) and import them as gold image and deploy the same to the target, these are also good steps to tests. FPP@Vagrant is offering a base env to test, it's up2you to do what you think it's good to test...
About your FPP question... looks to me the FPP server can not connect the target "fpp-Client"... you must have ""fpp-Client" in the DNS or in /etc/hosts on FPP server

**Comment by brokedba** [comment]
Thank you @rcitton. That's what I did and will post my fork link here once I cleaned it.
For my issue , I think I could connect because If the password is wrong It doesn't even start . I first taught my command was wrong but you seem to confirm it's valid .
```
[vagrant@fpp-Server ~]$ cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
# Public host info
192.168.78.101  fpp-Server.evilcorp.com  fpp-Server
192.168.78.102  fpp-Client.evilcorp.com  fpp-Client
# Private host info
192.168.100.101  fpp-Server-priv.evilcorp.com   fpp-Server-priv

# Virtual host info
192.168.78.201  fpp-Server-vip.evilcorp.com    fpp-Server-vip

# SCAN
192.168.78.151    london-fleet-scan.evilcorp.com    london-fleet-scan
192.168.78.152    london-fleet-scan.evilcorp.com    london-fleet-scan
192.168.78.153    london-fleet-scan.evilcorp.com    london-fleet-scan


[vagrant@fpp-Server ~]$ ping fpp-Client
PING fpp-Client.evilcorp.com (192.168.78.102) 56(84) bytes of data.
64 bytes from fpp-Client.evilcorp.com (192.168.78.102): icmp_seq=1 ttl=64 time=1.31 ms
64 bytes from fpp-Client.evilcorp.com (192.168.78.102): icmp_seq=2 ttl=64 time=0.316 ms
64 bytes from fpp-Client.evilcorp.com (192.168.78.102): icmp_seq=3 ttl=64 time=0.367 ms
```

- And I can log remotely to the server 

```
[root@fpp-Server ~]# ssh fpp-Client
root@fpp-client's password:
Last login: Mon Aug 10 17:13:40 2020 from 192.168.78.101

Welcome to Oracle Linux Server release 7.4 (GNU/Linux 4.1.12-112.16.4.el7uek.x86_64)

The Oracle Linux End-User License Agreement can be viewed here:

    * /usr/share/eula/eula.en_US

For additional packages, updates, documentation and community help, see:

    * http://yum.oracle.com/

[root@fpp-Client ~]#
```
The only thing I changed to ship host2 with a database is the ownership of u01/ (oracle instead of grid)
```
[root@fpp-Client ~]# ll /u01/
total 0
drwxrwxr-x. 6 oracle oinstall 68 Aug  6 01:54 app
```
still find this odd

**Comment by brokedba** [comment]
Anyone  ? 🙁

**Comment by brokedba** [comment]
I tried to check the logs and I still don't why this is happening. Could  anyone  help?
thank you

**Comment by rcitton** [comment]
See if exporting as NFS a filesystem from fpp-server you can mount it on fpp-client...

**Comment by brokedba** [comment]
Thanks @rcitton I will the vms back and check it out .

**Comment by brokedba** [comment]
- I added /home  directory to the exports on the FPP-Server
```
[root@fpp-Server ~]# systemctl status nfs-server
● nfs-server.service - NFS server and services
   Loaded: loaded (/usr/lib/systemd/system/nfs-server.service; enabled; vendor preset: disabled)
  Drop-In: /run/systemd/generator/nfs-server.service.d
           └─order-with-mounts.conf
   Active: active (exited) since Tue 2020-11-03 02:23:56 -04; 23min ago
  Process: 8597 ExecReload=/usr/sbin/exportfs -r (code=exited, status=0/SUCCESS)
 Main PID: 31910 (code=exited, status=0/SUCCESS)
```
- And I could mount it from the FPP-target without problem .

```[root@fpp-Client ~]# showmount -e fpp-Server
Export list for fpp-Server:
/home fpp-Client.evilcorp.com
[root@fpp-Client ~]# mkdir /mnt/FPPserver-home
[root@fpp-Client ~]# mount fpp-Server:/home /mnt/FPPserver-home/
[root@fpp-Client ~]# cd /mnt/FPPserver-home/
[root@fpp-Client FPPserver-home]# ll
total 16
drwx------. 4 grid    oinstall 4096 Aug  6 23:29 grid
drwx------. 3 oracle  oinstall   88 Aug  6 01:01 oracle
-rw-r--r--. 1 root    root     8685 Mar 15  2018 rpm.list
drwx------. 3 vagrant vagrant    95 Aug 15 19:32 vagrant
```

so it's not a mount problem . What if this is just a bug of FPP ? meaning that FPPserver can't import an image from an existing db_home in a target server .

**Comment by brokedba** [comment]
Ok , this is super weird but the operation works now. Maybe because I started the nfs service, I'll have to test it again from a fresh build. 
```
[grid@fpp-Server]$ rhpctl import image -image db_12102 -imagetype ORACLEDBSOFTWARE -path /u01/app/oracle/product/12.1.0.2/dbhome_1 -targetnode fpp-Client
 -root
Enter user "root" password:
fpp-Server.evilcorp.com: Adding storage for image ...
fpp-Server.evilcorp.com: Creating a new ACFS file system for image "db_12102" ...
fpp-Server.evilcorp.com: Starting export file system...
fpp-Server.evilcorp.com: Mounting file system...
fpp-Server.evilcorp.com: Copying files...
fpp-Server.evilcorp.com: Removing export file system ...
```
-  I see it too when I query the image : 
```
[grid@fpp-Server ~]$ rhpctl query image -image db_12102
fpp-Server.evilcorp.com: Audit ID: 17
Image name: db_12102
Owner: grid@london-fleet-c
Site: london-fleet-c
Access control: USER:grid@london-fleet-c
Access control: ROLE:OTHER
Access control: ROLE:GH_IMG_PUBLISH
Access control: ROLE:GH_IMG_ADMIN
Access control: ROLE:GH_IMG_VISIBILITY
Parent Image:
Software home path: /rhp_storage/images/idb_12102399207/swhome
Image state: PUBLISHED
Image size: 5320 Megabytes
Image Type: ORACLEDBSOFTWARE
Image Version: 12.1.0.2.0
Groups configured in the image: OSDBA=dba,OSBACKUP=dba,OSDG=dba,OSKM=dba
Image platform: Linux_AMD64
Interim patches installed:
Contains a non-rolling patch: FALSE
Complete: TRUE
```

The question is what now :) . any documentation on how to patch/upgrade an imported 12c to 19c ?

**Comment by brokedba** [comment]
The documentation links were provided by Ruggero .
 
- [ Patching Oracle Database Software](https://docs.oracle.com/en/database/oracle/oracle-database/19/cwadd/rapid-home-provisioning.html#GUID-CD92C0DB-D5E2-427A-8784-94F4C140B279) 
- [Upgrading Oracle Database Software](https://docs.oracle.com/en/database/oracle/oracle-database/19/cwadd/rapid-home-provisioning.html#GUID-3EDC1553-8411-4363-BCDC-DF4687AB3D60) 

closing this issue.

**Comment by brokedba** [comment]
Forgot to share the vagrant build repo from where all the above was experimented. 
[https://github.com/brokedba/OracleFPP](url)
cheers
[
![image](https://user-images.githubusercontent.com/29458929/100491479-d8f33080-30f1-11eb-9e55-656f570368c5.png)
](url)

**Comment by rcitton** [comment]
reopened ?

**Comment by brokedba** [comment]
Hi Ruggero , I think the fact the closed issues are not displayed by default in Github . While I just provided additional information regarding the environment (fork) where the issues happened and tackled , Once the issue is closed nobody can benefit from it's content is there a way to keep the closed issues visible ?
Thank you

**Comment by mark-au** [comment]
An issue in Open state suggests that something is incomplete. Closed issues are included in search results but I agree the `is:open` is default. If you think something is lacking, could you suggest a change to `OracleFPP/README.md` and then we can close the issue?

**Comment by brokedba** [comment]
At this point , the default display is more due to Github setting (unless you can modify the default view) and I can't think of something relevant to add in the Read.me. The fact that this issue was more an enhancement request to provide a build shipped with a 12c database and allow the import of its non image based Oracle Home to FPP-server makes it worth reading. Having implemented that enhancement myself on my [neo-fork](https://github.com/brokedba/OracleFPP)  is not worth a PR to the master branch but I can tell you what I did to make the import work which is adding the following line to [vagrant-projects\OracleFPP\scripts\12_Setup_FPP.sh](https://github.com/brokedba/OracleFPP/blob/master/scripts/12_Setup_FPP.sh)

```
echo '=== Enabling NFS SERVER ===' 
echo 
systemctl enable nfs-server
systemctl start nfs-server
#----------------------------------------------------------
# EndOfFile
#----------------------------------------------------------
```
You can close it but that would be too bad for those who might face the same challenges and likely waste time on something that's already fixed here.
