### ISSUE TITLE
VirtualBox-6.1.6-r137129-Win.msi

### ISSUE THREAD

**Issue by Umanoid1** [oracle/vagrant-projects#293]
Hi, kindly I have a problem in WINDOWS10 installing a new version, in a nutshell I can no longer update Vb because the file VirtualBox-6.1.6-r137129-Win.msi, I can't find it anymore, so I can't install the new version and not even uninstall, I also made a mistake I deleted some files, folders and log files manually without solving the problem, I had never had such a problem, the .MSI file downloaded by you, and not it I find more if you can kindly help me to find the .MSI file or give me a solution, in the faq I have not found the solution.

**Comment by Umanoid1** [comment]
No comet

**Comment by PaulNeumann** [comment]
@Umanoid1 It might be better to ask about this in the VirtualBox forums at [https://forums.virtualbox.org](https://forums.virtualbox.org).

However, you can download the VirtualBox 6.1.6 installer (VirtualBox-6.1.6-137129-Win.exe) from [https://download.virtualbox.org/virtualbox/6.1.6](https://download.virtualbox.org/virtualbox/6.1.6). Re-running the VirtualBox 6.1.6 installer might fix the problem, depending on what files and folders were deleted.

I hope this helps.

**Comment by Umanoid1** [comment]
Salve, Sig paulNeumann, il mio problema e trovare il file MSI, ho fatto quello che mi ha detto ma non ce stato nessun risultato, ho provato nel forum virtualbox ma nessuno sa come risolvere, una volta mi era successo ho dovuto formattare il pc, siccome non ho intenzione di formattare comunque grazie.

**Comment by PaulNeumann** [comment]
@Umanoid1 You can extract the MSI file from the EXE installer. First, download the VirtualBox 6.1.6 installer (VirtualBox-6.1.6-137129-Win.exe) from [https://download.virtualbox.org/virtualbox/6.1.6](https://download.virtualbox.org/virtualbox/6.1.6). Then run the following command in a Command Prompt or PowerShell window:

```
VirtualBox-6.1.6-137129-Win.exe -extract
```

This will extract the MSI file (VirtualBox-6.1.6-r137129.msi) to a temporary directory and display a message with the directory path (usually `%TEMP%\VirtualBox`).

I hope this helps.

**Comment by Umanoid1** [comment]
Buonasera, sig PaulNeumann, grazie per avermi risposto, ma il comando non ha funzionato, ma facendo qualche ricerca ho risolto il problema file MSI mancante, e installato la nuova versione quindi questo post si può chiudere.
