### ISSUE TITLE
Vagrantfile for Oracle WebLogic Server 

### ISSUE THREAD

**Issue by jacobt123** [oracle/vagrant-projects#297]
Creating this issue for a pull request to contribute a Vagrantfile I created for a multi-node WebLogic Server Cluster on Oracle Linux 7

**Comment by jacobt123** [comment]
I am an Oracle employee from the WLS team. Not sure if I still need to sign the OCA.

**Comment by Djelibeybi** [comment]
You don't, but you do need to be a member of OGHO, which you currently are not. Please contact me via Slack or email and I'll point you towards the process documentation.
