### ISSUE TITLE
container-runtime.sh: No such file or directory

### ISSUE THREAD

**Issue by streethawkz** [oracle/vagrant-projects#300]
Looks like there is an issue with Docker Vagrant image.

xx@DESKTOP-160CL9H MINGW64 /d/Vagrant_Box/vagrant-projects/DockerEngine (master)
$ vagrant reload --provision
==> vagrant: You have requested to enabled the experimental flag with the following features:
==> vagrant:
==> vagrant: Features:  disks
==> vagrant:
==> vagrant: Please use with caution, as some of the features may not be fully
==> vagrant: functional yet.
==> ol7-docker-engine: Attempting graceful shutdown of VM...
==> ol7-docker-engine: Checking if box 'oraclelinux/7' version '7.8.142' is up to date...
==> ol7-docker-engine: Clearing any previously set forwarded ports...
==> ol7-docker-engine: Clearing any previously set network interfaces...
==> ol7-docker-engine: Preparing network interfaces based on configuration...
    ol7-docker-engine: Adapter 1: nat
==> ol7-docker-engine: Forwarding ports...
    ol7-docker-engine: 22 (guest) => 2222 (host) (adapter 1)
==> ol7-docker-engine: Configuring storage mediums...
==> ol7-docker-engine: Running 'pre-boot' VM customizations...
==> ol7-docker-engine: Booting VM...
==> ol7-docker-engine: Waiting for machine to boot. This may take a few minutes...
    ol7-docker-engine: SSH address: 127.0.0.1:2222
    ol7-docker-engine: SSH username: vagrant
    ol7-docker-engine: SSH auth method: private key
==> ol7-docker-engine: Machine booted and ready!
==> ol7-docker-engine: Checking for guest additions in VM...
==> ol7-docker-engine: Setting hostname...
==> ol7-docker-engine: Mounting shared folders...
    ol7-docker-engine: /vagrant => D:/Vagrant_Box/vagrant-projects/DockerEngine
==> ol7-docker-engine: Running provisioner: shell...
    ol7-docker-engine: Running: C:/Users/xx/AppData/Local/Temp/vagrant-shell20200911-13096-e08bgx.sh
    ol7-docker-engine: /tmp/vagrant-shell: line 1: ../../OracleLinux/7/scripts/container-runtime.sh: No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by AmedeeBulle** [comment]
This is strange -- it might be related to the way _Symbolic Links_ are handled in Windows; I need to find a Windows box to investigate...

As workaround, remove `scripts/install.sh` and replace it by a copy of `../../OracleLinux/7/scripts/container-runtime.sh`

Alternatively, you can use the _OracleLinux/7_ project with the _Container Runtime_ extension (see [Oracle Container Runtime for Docker](https://github.com/oracle/vagrant-projects/tree/master/OracleLinux/7#oracle-container-runtime-for-docker)); the end result will be exactly the same.

**Comment by AmedeeBulle** [comment]
I assume you use _GIT for Windows_ / _GIT Bash_.

Please ensure you checked the **Enable symbolic links** option in the _Configuring extra options_ when you installed it.

If you re-install _GIT for Windows_ you will need to checkout the vagrant-project repo again to get the symlinks properly setup.

**Comment by streethawkz** [comment]
> I assume you use _GIT for Windows_ / _GIT Bash_.
> 
> Please ensure you checked the **Enable symbolic links** option in the _Configuring extra options_ when you installed it.
> 
> If you re-install _GIT for Windows_ you will need to checkout the vagrant-project repo again to get the symlinks properly setup.

tried this but I still see the same issue.
Reinstalled git with ënable symbolic links"
Restarted machine
vagrant destroy -f
cloned the repo again

But it still dint work 
==> ol7-docker-engine: Machine booted and ready!
==> ol7-docker-engine: Checking for guest additions in VM...
==> ol7-docker-engine: Setting hostname...
==> ol7-docker-engine: Mounting shared folders...
    ol7-docker-engine: /vagrant => D:/Vagrant_Box/vagrant-projects/DockerEngine
==> ol7-docker-engine: Running provisioner: shell...
    ol7-docker-engine: Running: C:/Users/Puneeth/AppData/Local/Temp/vagrant-shell20200911-12708-ty75q2.sh
    ol7-docker-engine: /tmp/vagrant-shell: line 1: ../../OracleLinux/7/scripts/container-runtime.sh: No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.


Kubernetes vagrant image seems to be working fine.
I have issues with only this one.

**Comment by streethawkz** [comment]
> This is strange -- it might be related to the way _Symbolic Links_ are handled in Windows; I need to find a Windows box to investigate...
> 
> As workaround, remove `scripts/install.sh` and replace it by a copy of `../../OracleLinux/7/scripts/container-runtime.sh`


Did not work. I get he same error :(

**Comment by streethawkz** [comment]
> > This is strange -- it might be related to the way _Symbolic Links_ are handled in Windows; I need to find a Windows box to investigate...
> > As workaround, remove `scripts/install.sh` and replace it by a copy of `../../OracleLinux/7/scripts/container-runtime.sh`
> 
> Did not work. I get he same error :(

Edited the install.sh file and gave the full path for container-runtime.sh - but I get the same error.

**Comment by AmedeeBulle** [comment]
> > This is strange -- it might be related to the way _Symbolic Links_ are handled in Windows; I need to find a Windows box to investigate...
> > As workaround, remove `scripts/install.sh` and replace it by a copy of `../../OracleLinux/7/scripts/container-runtime.sh`
> 
> Did not work. I get he same error :(

That doesn't make sense...
If you **replaced** the `scripts/install.sh` file by the `../../OracleLinux/7/scripts/container-runtime.sh` file, there is no way you can get the same error.

That is: (from _GIT Bash_)
```shell
rm scripts/install.sh
cp ../../OracleLinux/7/scripts/container-runtime.sh scripts/install.sh
```

As for:
> > Please ensure you checked the **Enable symbolic links** option in the _Configuring extra options_ when you installed it.
> > If you re-install _GIT for Windows_ you will need to checkout the vagrant-project repo again to get the symlinks properly setup.
> 
> tried this but I still see the same issue.

Do you have the required `SeCreateSymbolicLink` privilege as mentioned in the GIT installer dialog box?
If you see:
```shell
$ ls -l vagrant-projects/DockerEngine/scripts/install.sh
-rw-r--r-- 1 PVANHAES 197121 48 Sep 11 13:38 vagrant-projects/DockerEngine/scripts/install.sh
```
it is not checked out properly

You should have:
```shell
$ ls -l vagrant-projects/DockerEngine/scripts/install.sh
lrwxrwxrwx 1 PVANHAES 197121 48 Sep 11 13:21 vagrant-projects/DockerEngine/scripts/install.sh -> ../../OracleLinux/7/scripts/container-runtime.sh*
```
(If you don't have the privilege, the easiest is probably to _clone_ as _administrator_)

With this setup it builds fine on my Windows 10 environment:

```bash
PVANHAES@pvanhaes-win MINGW64 ~/src/vagrant-projects/DockerEngine (master)
$ vagrant up
==> vagrant: You have requested to enabled the experimental flag with the following features:
==> vagrant:
==> vagrant: Features:  disks
==> vagrant:
==> vagrant: Please use with caution, as some of the features may not be fully
==> vagrant: functional yet.
Bringing machine 'ol7-docker-engine' up with 'virtualbox' provider...
==> ol7-docker-engine: Importing base box 'oraclelinux/7'...
...
==> ol7-docker-engine: Mounting shared folders...
    ol7-docker-engine: /vagrant => C:/Users/PVANHAES/src/vagrant-projects/DockerEngine
==> ol7-docker-engine: Running provisioner: shell...
    ol7-docker-engine: Running: C:/Users/PVANHAES/AppData/Local/Temp/vagrant-shell20200911-232-1u5i8tj.sh
    ol7-docker-engine: Installing and configuring Oracle Container Runtime for Docker
...
    ol7-docker-engine: Complete!
    ol7-docker-engine: Creating 'btrfs' file system on: /dev/sdb
    ol7-docker-engine: Created symlink from /etc/systemd/system/multi-user.target.wants/docker.service to /usr/lib/systemd/system/docker.service.
    ol7-docker-engine: Oracle Container Runtime for Docker is ready to use
    ol7-docker-engine: To get started, on your host, run:
    ol7-docker-engine:   vagrant ssh
    ol7-docker-engine:
    ol7-docker-engine: Then, within the guest (for example):
    ol7-docker-engine:   docker run -it --rm oraclelinux:8-slim

PVANHAES@pvanhaes-win MINGW64 ~/src/vagrant-projects/DockerEngine (master)
```

**Comment by streethawkz** [comment]
> is setup it builds fine on my Windows 10 en

Issue was resolved after starting GIT Bash as Administrator.
Thank you so much for your help.

**Comment by AmedeeBulle** [comment]
I'm glad this helped.

Closing the issue as it is resolved.
