### ISSUE TITLE
Stderr: VBoxManage.exe: error: Argument --type must be specified

### ISSUE THREAD

**Issue by draoch** [oracle/vagrant-projects#302]
I am trying to steup oracle rac 12,2 on my laptop and encountering below error

Vagrant provider : virtual box. 

please could you advise the way forward
debug info below

==> node2: Running 'pre-boot' VM customizations...
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "modifyvm", "748261c6-a4db-46f1-b7ef-03c668ecbaed", "--memory", "6144"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "modifyvm", "748261c6-a4db-46f1-b7ef-03c668ecbaed", "--cpus", "2"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "modifyvm", "748261c6-a4db-46f1-b7ef-03c668ecbaed", "--groups", "/vgtol7-rac"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "storageattach", "748261c6-a4db-46f1-b7ef-03c668ecbaed", "--storagectl", "SATA Controller", "--port", "0", "--nonrotational", "on"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31999
DEBUG subprocess: Exit status: 0
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "storageattach", "748261c6-a4db-46f1-b7ef-03c668ecbaed", "--storagectl", "SATA Controller", "--port", "1", "--nonrotational", "on"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: VBoxManage.exe: error: Argument --type must be specified
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 1
 INFO retryable: Retryable exception raised: #<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["storageattach", "748261c6-a4db-46f1-b7ef-03c668ecbaed", "--storagectl", "SATA Controller", "--port", "1", "--nonrotational", "on"]

Stderr: VBoxManage.exe: error: Argument --type must be specified
>
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "storageattach", "748261c6-a4db-46f1-b7ef-03c668ecbaed", "--storagectl", "SATA Controller", "--port", "1", "--nonrotational", "on"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: VBoxManage.exe: error: Argument --type must be specified
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 1
 INFO retryable: Retryable exception raised: #<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["storageattach", "748261c6-a4db-46f1-b7ef-03c668ecbaed", "--storagectl", "SATA Controller", "--port", "1", "--nonrotational", "on"]

**Comment by AmedeeBulle** [comment]
Can you please edit the `Vagrantfile` and replace line [155](https://github.com/oracle/vagrant-projects/blob/master/OracleRAC/Vagrantfile#L155)  by
```
box_disks_num = 1
```
and let us know the outcome?

@rcitton the latest OL 7 box does not have an additional disk anymore -- I believe this is what is causing the trouble here...

**Comment by rcitton** [comment]
@AmedeeBulle , yes does not reproduce using oraclelinux/7 (virtualbox, 7.8.128), but reproduce using latest oraclelinux/7' (v7.8.142); and I can confirm with "box_disks_num = 1" at line 155 is solving.

**Comment by AmedeeBulle** [comment]
I would suggest to add a `config.vm.box_version` to the Vagrantfile to require 7.8.142 or above and change the `box_disks_num` at the same time, that way we would be covered if people have still older boxes locally...

**Comment by AmedeeBulle** [comment]
This should be fixed by #305  -- thanks @rcitton

**Comment by draoch** [comment]
Thx you guys... issue got resolved and RAC got deployed seamlessly
