### ISSUE TITLE
Metadata file does not match checksum

### ISSUE THREAD

**Issue by streethawkz** [oracle/vagrant-projects#303]
**Describe the issue**

Unable to start the DockerEnginer vagrant with the following error :

==> ol7-docker-engine: Running provisioner: shell...
    ol7-docker-engine: Running: C:/Users/THELEA~1/AppData/Local/Temp/vagrant-shell20200923-6340-131x2n1.sh
    ol7-docker-engine: Installing and configuring Oracle Container Runtime for Docker
    ol7-docker-engine: http://yum.oracle.com/repo/OracleLinux/OL7/latest/x86_64/repodata/b6aff104127f50a6ccc0ec80d54872a9164a49f7-updateinfo.xml.gz: [Errno -1] Metadata file does not match checksum
    ol7-docker-engine: Trying other mirror.
    ol7-docker-engine: http://yum.oracle.com/repo/OracleLinux/OL7/UEKR5/x86_64/repodata/9ea0c75efc04fe6a60ca2ead34b3d3da0fde8e43-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    ol7-docker-engine: Trying other mirror.
    ol7-docker-engine: http://yum.oracle.com/repo/OracleLinux/OL7/optional/latest/x86_64/repodata/fcc2060a0cdc00d7b20905a0f4398960c49fca1c-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    ol7-docker-engine: Trying other mirror.
    ol7-docker-engine: https://yum.oracle.com/repo/OracleLinux/OL7/SoftwareCollections/x86_64/repodata/3597a38ab765cb2786f74944e914f4a35596606d-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    ol7-docker-engine: Trying other mirror.
    ol7-docker-engine: https://yum.oracle.com/repo/OracleLinux/OL7/developer_EPEL/x86_64/repodata/7b956ffe8e0d1f7321161c74ff5b1115a847fe40-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    ol7-docker-engine: Trying other mirror.
    ol7-docker-engine: http://yum.oracle.com/repo/OracleLinux/OL7/latest/x86_64/repodata/ed4295fef335fe045a75a690c7b27fe1fd3d99d2-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    ol7-docker-engine: Trying other mirror.
    ol7-docker-engine: http://yum.oracle.com/repo/OracleLinux/OL7/UEKR5/x86_64/repodata/9ea0c75efc04fe6a60ca2ead34b3d3da0fde8e43-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    ol7-docker-engine: Trying other mirror.
    ol7-docker-engine: https://yum.oracle.com/repo/OracleLinux/OL7/developer_EPEL/x86_64/repodata/7b956ffe8e0d1f7321161c74ff5b1115a847fe40-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    ol7-docker-engine: Trying other mirror.
    ol7-docker-engine: http://yum.oracle.com/repo/OracleLinux/OL7/UEKR5/x86_64/repodata/9ea0c75efc04fe6a60ca2ead34b3d3da0fde8e43-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    ol7-docker-engine: Trying other mirror.
    ol7-docker-engine:
    ol7-docker-engine:
    ol7-docker-engine:  One of the configured repositories failed (Latest Unbreakable Enterprise Kernel Release 5 for Oracle Linux 7Server (x86_64)),
    ol7-docker-engine:  and yum doesn't have enough cached data to continue. At this point the only
    ol7-docker-engine:  safe thing yum can do is fail. There are a few ways to work "fix" this:
    ol7-docker-engine:
    ol7-docker-engine:      1. Contact the upstream for the repository and get them to fix the problem.
    ol7-docker-engine:
    ol7-docker-engine:      2. Reconfigure the baseurl/etc. for the repository, to point to a working
    ol7-docker-engine:         upstream. This is most often useful if you are using a newer
    ol7-docker-engine:         distribution release than is supported by the repository (and the
    ol7-docker-engine:         packages for the previous distribution release still work).
    ol7-docker-engine:
    ol7-docker-engine:      3. Run the command with the repository temporarily disabled
    ol7-docker-engine:             yum --disablerepo=ol7_UEKR5 ...
    ol7-docker-engine:
    ol7-docker-engine:      4. Disable the repository permanently, so yum won't use it by default. Yum
    ol7-docker-engine:         will then just ignore the repository until you permanently enable it
    ol7-docker-engine:         again or use --enablerepo for temporary usage:
    ol7-docker-engine:
    ol7-docker-engine:             yum-config-manager --disable ol7_UEKR5
    ol7-docker-engine:         or
    ol7-docker-engine:             subscription-manager repos --disable=ol7_UEKR5
    ol7-docker-engine:
    ol7-docker-engine:      5. Configure the failing repository to be skipped, if it is unavailable.
    ol7-docker-engine:         Note that yum will try to contact the repo. when it runs most commands,
    ol7-docker-engine:         so will have to try and fail each time (and thus. yum will be be much
    ol7-docker-engine:         slower). If it is a very temporary problem though, this is often a nice
    ol7-docker-engine:         compromise:
    ol7-docker-engine:
    ol7-docker-engine:             yum-config-manager --save --setopt=ol7_UEKR5.skip_if_unavailable=true
    ol7-docker-engine:
    ol7-docker-engine: failure: repodata/9ea0c75efc04fe6a60ca2ead34b3d3da0fde8e43-primary.sqlite.bz2 from ol7_UEKR5: [Errno 256] No more mirrors to try.
    ol7-docker-engine: http://yum.oracle.com/repo/OracleLinux/OL7/UEKR5/x86_64/repodata/9ea0c75efc04fe6a60ca2ead34b3d3da0fde8e43-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    ol7-docker-engine: /tmp/vagrant-shell: line 21: docker-storage-config: command not found
    ol7-docker-engine: Failed to start docker.service: Unit not found.
    ol7-docker-engine: Failed to execute operation: No such file or directory

**Environment (please complete the following information):**

- Host OS: Windows 10 Pro
- Vagrant version: Vagrant 2.2.10
- Vagrant provider:
  - For VirtualBox:
    - VirtualBox version: 6.1
  
- Vagrant project:  DockerEngine

**Comment by AmedeeBulle** [comment]
Checked with Puneeth, issue was caused by Hyper-V on the host.

For reference, it is not enough to uninstall Hyper-V, you also need to run

```
bcdedit /set hypervisorlaunchtype off
```

and reboot.
