### ISSUE TITLE
Could not unmarshal JSON result for kubernetes-control-plane on xxx invalid character 'd' after object key:value pair

### ISSUE THREAD

**Issue by streethawkz** [oracle/vagrant-projects#304]
**Describe the issue**

I see the following error while starting OLCNE vagrant 👍    

master1: ===== Create the Kubernetes module for olcne-env  =====
    master1:     olcnectl module create --environment-name olcne-env --module kubernetes --name olcne-cluster --container-registry container-registry.oracle.com/olcne --nginx-image container-registry.oracle.com/olcne/nginx:1.12.2 --apiserver-advertise-address 192.168.99.101 --virtual-ip 192.168.99.99 --master-nodes 192.168.99.101:8090 --worker-nodes 192.168.99.111:8090,192.168.99.112:8090
    master1: ===== Validate all required prerequisites are met for the Kubernetes module =====
    master1:     olcnectl module validate --environment-name olcne-env --name olcne-cluster
    master1: ===== Deploy the Kubernetes module into olcne-env (Be patient!) =====
    master1:     olcnectl module install --environment-name olcne-env --name olcne-cluster
    master1: Returned a non-zero code: 1
    master1: Last output lines:
    master1: Encountered errors with 192.168.99.101:8090
    master1:   Could not unmarshal JSON result for kubernetes-control-plane on 192.168.99.101:8090: invalid character 'd' after object key:value pair ({"error":"Timeout after 300 second when running: /usr/libexec/kubeman [set kubernetes-control-plane {"desired_state":"installing","kubernetes_version":"1.17.9-1","image_repository":"container-registry.oracle.com/olcne","apiserver_advertise_address":"192.168.99.101","apiserver_cert_extra_sans":"","service_cidr":"10.96.0.0/12","pod_cidr":"10.244.0.0/16","apiserver_bind_port":"6444","kube_proxy_mode":"iptables","load_balancer":"192.168.99.99:6443","token":"","pod_network":"flannel","is_primary":"true","is_master":"true","join_command":"","upload_certificate_key":"8905a06dab4dfb0fd56c7772097dd2366743806d46ce6ef72d1c2eb11a663f0e","etcd_image_tag":"3.4.3-1","coredns_image_tag":"1.6.5-1","pod-network-iface":""}]", "user_action":[]})
    master1: See /var/tmp/cmd_le5db.log for details
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Environment (please complete the following information):**

- Host OS: Windows 10 Pro
- Vagrant version: Vagrant 2.2.10
- Vagrant provider:
  - For VirtualBox:
    - VirtualBox version: 6.1
 
- Vagrant project: OLCNE

**Comment by AmedeeBulle** [comment]
This error typically appears when it takes too long to provision nodes, in particular when downloading the container images.

It is recommended to use a registry mirror for the installation, see the [Repositories](../tree/master/OLCNE#repositories) section in the README.

Closing after reviewing this issue with Puneeth.
