### ISSUE TITLE
BUG: Vagrantfile references variable DOMAIN while setup.sh expects DOMAIN_NAME

### ISSUE THREAD

**Issue by simonpane** [oracle/vagrant-projects#308]
**Small bug:**

In file **OracleDG/Vagrantfile**,  an environment variable called `DOMAIN` is defined (from var_domain) and is passed to the provisioning script.  But the actual provisioning script **OracleDG/scripts/setup.sh** is expecting the variable to be called `DOMAIN_NAME`.

Consequently, the domain value specified in **vagrant.yml** is lost and never set in file **setup.env**.  And subsequently is not configured in guest configuration files such as /etc/hosts and /etc/resolv.conf.

For other subfolders, the variable export command is handled inconsistently:

```
$ grep -r "export\ DOMAIN" *
OracleDG/scripts/setup.sh:export DOMAIN_NAME=${DOMAIN_NAME}
OracleFPP/scripts/setup.sh:export DOMAIN_NAME=$DOMAIN
OracleRAC/scripts/setup.sh:export DOMAIN_NAME=localdomain
```

**Simple fix:** 
Adjust for consistency in all `scripts/setup.sh` files.

**Environment:**

- Affects all environments.
- Affects OracleDG, OracleFPP, and OracleRAC builds

**Comment by simonpane** [comment]
To re-submit with OCA sign-off.

**Comment by Djelibeybi** [comment]
You don't need to close this issue for the OCA. I'll tag your PR accordingly.
