### ISSUE TITLE
not all versions have rpm files for downloading

### ISSUE THREAD

**Issue by ozbillwang** [oracle/vagrant-projects#313]
**Describe the issue**

problem in Vagrant box for `OracleDatabase/11.2.0.2`

the install script need a zip file and after unzip, it need be a rpm installation file

https://github.com/oracle/vagrant-projects/blob/master/OracleDatabase/11.2.0.2/scripts/install.sh#L41-L46

```
# install Oracle
unzip /vagrant/oracle-xe-11.2.0-1.0.x86_64.rpm.zip -d /tmp
sudo rpm -i /tmp/Disk1/oracle-xe-11.2.0-1.0.x86_64.rpm
chmod -R u+w /tmp/Disk1
rm -rf /tmp/Disk1
sudo ln -s /u01/app/oracle /opt/oracle
```

But I got 2 zip files, after unzip, they are not rpm file at all, they are plat files with a lot of jar files, the `runInstallation` script which need Xwindown Disploy setup, it is not easy to enable on Vagrant box.

**Comment by PaulNeumann** [comment]
@ozbillwang It sounds like you might have downloaded the wrong zip file, or the download got corrupted. The zip file for the OracleDatabase/11.2.0.2 project is named `oracle-xe-11.2.0-1.0.x86_64.rpm.zip`. It should be 315,891,481 bytes, and it should have the following checksums:

- CRC32: 5C05FA9E
- CRC64: D1E986D5BDDA45E3
- SHA1: 996ED9C6C85ADEDDB86A77EDB1AEAF483A8B2AB8
- SHA256: B5039FAD2E4F92C68778DCABBD0B4622A6CB025F25F7D6222F9E9DE53EBAB531

To download the zip file, browse to [http://www.oracle.com/technetwork/database/enterprise-edition/downloads/index.html](http://www.oracle.com/technetwork/database/enterprise-edition/downloads/index.html). Near the bottom of the page, under the **Oracle Database Express Edition** heading, click on the "Oracle Database 11g Release 2 Express Edition for Linux x86 and Windows" link. That will open the **Oracle Database XE Prior Release Archive** page. Click on the "Oracle Database 11gR2 Express Edition for Linux x64" link to download the zip file.

I hope this helps.

**Comment by ozbillwang** [comment]
Thanks, @PaulNeumann 

I found the url at https://download.oracle.com/otn/linux/oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip

Seems it is not SE (standard) or EE (enterprise Edition), but Express Edition

That's good enough. Thanks again.

**Comment by ozbillwang** [comment]
By the way @PaulNeumann 

I can't use username and password to connect the database. 

What username I should use? I have run `setPassword.sh` to set the password. 

```
sqlplus / as sysdba << EOF
      ALTER USER SYS IDENTIFIED BY "$ORACLE_PWD";
      ALTER USER SYSTEM IDENTIFIED BY "$ORACLE_PWD";
      exit;
EOF
```

But if I try login with SYS or SYSTEM, seems i can't

**Comment by PaulNeumann** [comment]
@ozbillwang The `setPassword.sh` script for the OracleDatabase/11.2.0.2 project can be a little finicky, so it's sometimes easier to set the SYS and SYSTEM passwords manually. Here's how to do that:

- ssh to the VM
- Change to the oracle user using the command `sudo su - oracle`
- Start SQL*Plus using the command `sqlplus / as sysdba`
- Set the SYS and SYSTEM passwords to whatever you'd like using the `ALTER USER` command:
   `ALTER USER SYS IDENTIFIED BY NewPassword;`
   `ALTER USER SYSTEM IDENTIFIED BY NewPassword;`
   `exit`

I hope this helps.
