### ISSUE TITLE
vagrant@127.0.0.1: Permission denied (publickey,gssapi-keyex,gssapi-with-mic). #9831

### ISSUE THREAD

**Issue by eswar8086** [oracle/vagrant-projects#314]
**Describe the issue**

A clear and concise description of what the issue is.  
Explain what commands you ran, what you expected to happen and what actually happened.

**Environment (please complete the following information):**

- Host OS: [e.g. Oracle Linux 8, macOS 10.14.6, Windows 10 Pro, ...]
- Kernel version (for Linux host): [run `uname -a`]
- Vagrant version: [e.g. 2.2.9]
- Vagrant provider:
  - For VirtualBox:
    - VirtualBox version: [e.g. 6.1.8r137981 -- run `vboxmanage -v`]
  - For libvirt:
    - Vagrant-libvirt plugin version: [e.g. 0.1.2 -- run `vagrant plugin list`]
    - QEMU and libvirt version:  
      If you have `virsh` installed run `virsh -c qemu:///system version --daemon`  
      Alternatively query your package manager with e.g.  
        `rpm -q qemu-kvm libvirt`,  
        `dpkg -l qemu-kvm libvirt\* | grep ^ii`, ...
- Vagrant project:  [e.g. OLCNE, OracleDatabase/19.3.0, ...]

**Additional information**

Add any other information about the issue here (console log, ...).

**Comment by PaulNeumann** [comment]
@eswar8086 Based on the issue title, it appears that you're unable to connect to a Vagrant VM using ssh, but there's not enough information to help. Please provide the information requested in the issue template.

**Comment by eswar8086** [comment]
Thankyou for your quick response.
I have installed 18.4.0-XE using vagrant in my laptop.
Post installation when I tried to run vagrant ssh I am getting billow error
Please help me to fix issue asap

D:\ORACLE TRINING\vagrant-projects-master\vagrant-projects-master\OracleDatabase\18.4.0-XE>vagrant ssh
vagrant@127.0.0.1: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by totalamateurhour** [comment]
@eswar8086 do you have software running that acts as a proxy for ssh traffic? for example,  Proxifier? If so, please disable that.

**Comment by eswar8086** [comment]
Can you please help me how to disable

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Eswara T<mailto:cloud.eswar@outlook.com>
Sent: 13 October 2020 00:15
To: oracle/vagrant-projects<mailto:reply@reply.github.com>; oracle/vagrant-projects<mailto:vagrant-projects@noreply.github.com>
Cc: Mention<mailto:mention@noreply.github.com>
Subject: RE: [oracle/vagrant-projects] vagrant@127.0.0.1: Permission denied (publickey,gssapi-keyex,gssapi-with-mic). #9831 (#314)

Thankyou for your quick response.
I have installed 18.4.0-XE using vagrant in my laptop.
Post installation when I tried to run vagrant ssh I am getting billow error
Please help me to fix issue asap

D:\ORACLE TRINING\vagrant-projects-master\vagrant-projects-master\OracleDatabase\18.4.0-XE>vagrant ssh
vagrant@127.0.0.1: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by PaulNeumann** [comment]
@eswar8086 You haven't said what versions of Windows and Vagrant you're running, but this kind of problem is sometimes related to configuration files for the built-in Windows ssh client.

In the Command Prompt window, try running the command `SET VAGRANT_PREFER_SYSTEM_BIN=0` before running `vagrant ssh`. This tells Vagrant to use its own ssh client, instead of the Windows ssh client.

If that doesn't help, please post the output of the command `vagrant ssh --debug`.

**Comment by eswar8086** [comment]
Thanks for the update.
PFA ,vagrant ssh –debug output

Regards,
Eswara

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by eswar8086** [comment]
Can you please help me here.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Eswara T<mailto:cloud.eswar@outlook.com>
Sent: 14 October 2020 08:37
To: oracle/vagrant-projects<mailto:reply@reply.github.com>; oracle/vagrant-projects<mailto:vagrant-projects@noreply.github.com>
Cc: Mention<mailto:mention@noreply.github.com>
Subject: RE: [oracle/vagrant-projects] vagrant@127.0.0.1: Permission denied (publickey,gssapi-keyex,gssapi-with-mic). #9831 (#314)

Thanks for the update.
PFA ,vagrant ssh –debug output

Regards,
Eswara

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by PaulNeumann** [comment]
@eswar8086 It's very difficult to help without complete information.

1. Do you have any software running that acts as a proxy for ssh traffic?
1. Do you get the same error when you use Vagrant's built-in ssh client (i.e., running `SET VAGRANT_PREFER_SYSTEM_BIN=0` before running `vagrant ssh`)?
1. The output you posted from `vagrant ssh --debug` is incomplete. Please provide the entire output. Because the output is fairly long, it would be better to copy it to a gist and then post a link to the gist here.

**Comment by eswar8086** [comment]
Team,
While running Vagrant up I have below error. It seems required RPM’s not available. Are these need to download from site ?


Oracle11g-xe-vagrant: INSTALLER: Oracle directories created
    oracle11g-xe-vagrant: unzip:  cannot find or open /vagrant/oracle-xe-11.2.0-1.0.x86_64.rpm.zip, /vagrant/oracle-xe-11.2.0-1.0.x86_64.rpm.zip.zip or /vagrant/oracle-xe-11.2.0-1.0.x86_64.rpm.zip.ZIP.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

D:vagrant-projects-master\vagrant-projects-master\OracleDatabase\11.2.0.2>

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mark-au** [comment]
Yes you need to download that RPM manually, see the [Getting Started](https://github.com/oracle/vagrant-projects/tree/master/OracleDatabase/11.2.0.2#getting-started) documentation

**Comment by totalamateurhour** [comment]
Closed due to lack of follow up.
