### ISSUE TITLE
OracleDG : GLOBAL_DBNAME is not setup properly for NODE2_HOSTNAME in 07_setup_OracleNet.sh

### ISSUE THREAD

**Issue by rene-ace** [oracle/vagrant-projects#316]
**Describe the issue**

GLOBAL_DBNAME is not setup properly for NODE2_HOSTNAME in 07_setup_OracleNet.sh.

**Environment (please complete the following information):**

- Vagrant project:  [OracleDG]

**Additional information**
Getting error ORA-12520 due to GLOBAL_DBNAME not being setup properly for ${DB_NAME}_STDBY

DGMGRL> validate database db193h1_stdby;
  Database Role:    Primary database
  Ready for Switchover:  Yes
  Flashback Database Status:
    db193h1_stdby:  Off
  Managed by Clusterware:
    db193h1_stdby:  NO             
    Validating static connect identifier for the primary database db193h1_stdby...
Unable to connect to database using (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=standby)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=DB193H1_STDBY_DGMGRL)(INSTANCE_NAME=DB193H1)(SERVER=DEDICATED)(STATIC_SERVICE=TRUE)))
ORA-12520: TNS:listener could not find available handler for requested type of server
Failed.
    Warning: Ensure primary database's StaticConnectIdentifier property
    is configured properly so that the primary database can be restarted
    by DGMGRL after switchover

**Fix**
Change line 95 in 07_setup_OracleNet.sh
From :       (GLOBAL_DBNAME = ${DB_NAME}_DGMGRL)
To :       (GLOBAL_DBNAME = ${DB_NAME}_STDBY_DGMGRL)

**Comment by rcitton** [comment]
Hi @rene-ace thank you, Ive fixed the issue, waiting on merge #319

**Comment by rcitton** [comment]
the merge is done please check

**Comment by rcitton** [comment]
Please close this issue as already fixed  on Oct 30, 2020

**Comment by totalamateurhour** [comment]
Closing per @rcitton
