### ISSUE TITLE
OracleDG : switchover fails due to local_listener not being setup properly

### ISSUE THREAD

**Issue by rene-ace** [oracle/vagrant-projects#317]
**Describe the issue**

Switchover fails due to local_listener not being setup properly in primary_DB_setup.sh and standby_DB_setup.sh

**Environment (please complete the following information):**

Vagrant project: [OracleDG]

**Additional information**
After workaround of Issue [OracleDG : GLOBAL_DBNAME is not setup properly for NODE2_HOSTNAME in 07_setup_OracleNet.sh](https://github.com/oracle/vagrant-projects/issues/316)

When executing the switchover to db193h1_stdby, it fails due to the db193h1_stdby and db193h1 service not being registered in the LISTENER.

When I executed the following
SQL> alter system set local_listener='(ADDRESS=(PROTOCOL=TCP)(HOST=standby)(PORT=1521))';

System altered.

SQL> alter system register;

System altered.

After this, I recreate the DG configuration, it works as expected

When local_listener is not set up properly
e.g.
[oracle@primary ~]$ dgmgrl sys@DB193H1
DGMGRL for Linux: Release 19.0.0.0.0 - Production on Tue Oct 27 12:26:53 2020
Version 19.9.0.0.0

Copyright (c) 1982, 2019, Oracle and/or its affiliates. All rights reserved.

Welcome to DGMGRL, type "help" for information.
Password:
Connected to "DB193H1"
Connected as SYSDBA.
DGMGRL> switchover to 'db193h1_stdby';
Performing switchover NOW, please wait...
Operation requires a connection to database "db193h1_stdby"
Connecting ...
Connected to "DB193H1_STDBY"
Connected as SYSDBA.
Error: ORA-1034: ORACLE not available
Error: ORA-16625: cannot reach member "db193h1"

Failed.
Unable to switchover, primary database is still "db193h1"

When local_listener is set up properly
e.g.
DGMGRL> switchover to db193h1_stdby;
Performing switchover NOW, please wait...
Operation requires a connection to database "db193h1_stdby"
Connecting ...
Connected to "DB193H1_STDBY"
Connected as SYSDBA.
New primary database "db193h1_stdby" is opening...
Operation requires start up of instance "DB193H1" on database "db193h1"
Starting instance "DB193H1"...
Connected to an idle instance.
ORACLE instance started.
Connected to "DB193H1"
Database mounted.
Database opened.
Connected to "DB193H1"
Switchover succeeded, new primary is "db193h1_stdby"

**Fix**
Add to primary_DB_setup.sh: 
alter system set local_listener='(ADDRESS=(PROTOCOL=TCP)(HOST=${NODE1_HOSTNAME})(PORT=1521))';
alter system register;

Add to standby_DB_setup.sh: 
alter system set local_listener='(ADDRESS=(PROTOCOL=TCP)(HOST=${NODE2_HOSTNAME})(PORT=1521))';
alter system register;

**Comment by rcitton** [comment]
Hi @rene-ace thank you, Ive fixed the issue, waiting on merge #319

**Comment by rcitton** [comment]
the merge is done please check

**Comment by rcitton** [comment]
Please close this issue as already fixed on Oct 30, 2020

**Comment by totalamateurhour** [comment]
Closing per @rcitton
