### ISSUE TITLE
OLCNE Deployment failure

### ISSUE THREAD

**Issue by rikumabokss** [oracle/vagrant-projects#321]
**Describe the issue**

Default run of "vagrant up". Setup failed with following error message:
master1:   Could not unmarshal JSON result for kubernetes-control-plane on 192.168.99.101:8090: invalid character 'd' after object key:value pair ({"error":"Timeout after 300 second when running: /usr/libexec/kubeman [set kubernetes-control-plane {"desired_state":"installing","kubernetes_version":"1.17.9-1","image_repository":"container-registry.oracle.com/olcne","apiserver_advertise_address":"192.168.99.101","apiserver_cert_extra_sans":"","service_cidr":"10.96.0.0/12","pod_cidr":"10.244.0.0/16","apiserver_bind_port":"6444","kube_proxy_mode":"iptables","load_balancer":"192.168.99.99:6443","token":"","pod_network":"flannel","is_primary":"true","is_master":"true","join_command":"","upload_certificate_key":"108010a298c7f1f9e005e97bd98d731a3efbc76f95853f77dbe26d9843855863","etcd_image_tag":"3.4.3-1","coredns_image_tag":"1.6.5-1","pod-network-iface":""}]", "user_action":[]})
    master1: See /var/tmp/cmd_szPYg.log for details
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
-----
Complete log:

[rikuma@desktop2 OLCNE]$ vagrant up
Bringing machine 'worker1' up with 'virtualbox' provider...
Bringing machine 'worker2' up with 'virtualbox' provider...
Bringing machine 'master1' up with 'virtualbox' provider...
==> worker1: Importing base box 'oraclelinux/7'...
==> worker1: Matching MAC address for NAT networking...
==> worker1: Checking if box 'oraclelinux/7' version '7.8.142' is up to date...
==> worker1: Setting the name of the VM: OLCNE_worker1_1605112341976_73790
==> worker1: Clearing any previously set network interfaces...
==> worker1: Preparing network interfaces based on configuration...
    worker1: Adapter 1: nat
    worker1: Adapter 2: hostonly
==> worker1: Forwarding ports...
    worker1: 22 (guest) => 2222 (host) (adapter 1)
==> worker1: Running 'pre-boot' VM customizations...
==> worker1: Booting VM...
==> worker1: Waiting for machine to boot. This may take a few minutes...
    worker1: SSH address: 127.0.0.1:2222
    worker1: SSH username: vagrant
    worker1: SSH auth method: private key
    worker1: Warning: Connection reset. Retrying...
    worker1:
    worker1: Vagrant insecure key detected. Vagrant will automatically replace
    worker1: this with a newly generated keypair for better security.
    worker1:
    worker1: Inserting generated public key within guest...
    worker1: Removing insecure key from the guest if it's present...
    worker1: Key inserted! Disconnecting and reconnecting using new SSH key...
==> worker1: Machine booted and ready!
==> worker1: Checking for guest additions in VM...
==> worker1: Setting hostname...
==> worker1: Mounting shared folders...
    worker1: /vagrant => /home/rikuma/Downloads/vagrant-projects/OLCNE
==> worker1: Running provisioner: shell...
    worker1: Running: /tmp/vagrant-shell20201111-77286-mc7qat.sh
    worker1: ===== Configure private network =====
    worker1:     ifup eth1
    worker1: ===== Configure YUM repos for Oracle Linux Cloud Native Environment =====
    worker1:     yum install -y jq
    worker1:     yum install -y yum-utils
    worker1:     yum install -y oracle-olcne-release-el7
    worker1:     yum-config-manager --disable ol7_olcne
    worker1:     yum-config-manager --enable ol7_olcne11
    worker1:     yum-config-manager --disable ol7_developer*
    worker1:     yum-config-manager --enable ol7_kvm_utils
    worker1: ===== Fulfil requirements =====
    worker1:     swapoff -a
    worker1:     sed -i '/ swap /d' /etc/fstab
    worker1:     modprobe br_netfilter
    worker1:     eval echo 'br_netfilter' > /etc/modules-load.d/br_netfilter.conf
    worker1:     /usr/sbin/setenforce 0
    worker1:     sed -i 's/^SELINUX=.*/SELINUX=permissive/g' /etc/selinux/config
    worker1:     systemctl enable --now firewalld
    worker1:     firewall-cmd --permanent --zone=public --add-interface=eth0
    worker1: ===== Installing the Oracle Linux Cloud Native Environment Platform Agent =====
    worker1:     yum install -y olcne-agent olcne-utils
    worker1:     yum install -y kubeadm kubelet kubectl
    worker1:     sysctl -p /etc/sysctl.d/k8s.conf
    worker1:     systemctl enable olcne-agent.service
    worker1:     firewall-cmd --zone=trusted --add-interface=cni0 --permanent
    worker1:     firewall-cmd --add-port=8090/tcp --permanent
    worker1:     firewall-cmd --add-port=10250/tcp --permanent
    worker1:     firewall-cmd --add-port=10255/tcp --permanent
    worker1:     firewall-cmd --add-port=8472/udp --permanent
    worker1:     firewall-cmd --add-port=30000-32767/tcp --permanent
    worker1:     systemctl restart firewalld
    worker1: ===== Allow passwordless ssh between VMs =====
    worker1: ===== Generating shared SSH keypair =====
    worker1:     ssh-keygen -t rsa -f /vagrant/id_rsa -q -N ''
    worker1:     mkdir /root/.ssh
    worker1:     cp /vagrant/id_rsa /root/.ssh/
    worker1:     cp /vagrant/id_rsa.pub /root/.ssh/authorized_keys
    worker1:     eval cat /vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    worker1:     chmod 0700 /root/.ssh
    worker1:     chmod 0600 /root/.ssh/authorized_keys /root/.ssh/id_rsa
    worker1: ===== Oracle Linux base software installation complete. =====
==> worker2: Importing base box 'oraclelinux/7'...
==> worker2: Matching MAC address for NAT networking...
==> worker2: Checking if box 'oraclelinux/7' version '7.8.142' is up to date...
==> worker2: Setting the name of the VM: OLCNE_worker2_1605112883196_11469
==> worker2: Fixed port collision for 22 => 2222. Now on port 2200.
==> worker2: Clearing any previously set network interfaces...
==> worker2: Preparing network interfaces based on configuration...
    worker2: Adapter 1: nat
    worker2: Adapter 2: hostonly
==> worker2: Forwarding ports...
    worker2: 22 (guest) => 2200 (host) (adapter 1)
==> worker2: Running 'pre-boot' VM customizations...
==> worker2: Booting VM...
==> worker2: Waiting for machine to boot. This may take a few minutes...
    worker2: SSH address: 127.0.0.1:2200
    worker2: SSH username: vagrant
    worker2: SSH auth method: private key
    worker2: Warning: Connection reset. Retrying...
    worker2: Warning: Remote connection disconnect. Retrying...
    worker2:
    worker2: Vagrant insecure key detected. Vagrant will automatically replace
    worker2: this with a newly generated keypair for better security.
    worker2:
    worker2: Inserting generated public key within guest...
    worker2: Removing insecure key from the guest if it's present...
    worker2: Key inserted! Disconnecting and reconnecting using new SSH key...
==> worker2: Machine booted and ready!
==> worker2: Checking for guest additions in VM...
==> worker2: Setting hostname...
==> worker2: Mounting shared folders...
    worker2: /vagrant => /home/rikuma/Downloads/vagrant-projects/OLCNE
==> worker2: Running provisioner: shell...
    worker2: Running: /tmp/vagrant-shell20201111-77286-12v7u2i.sh
    worker2: ===== Configure private network =====
    worker2:     ifup eth1
    worker2: ===== Configure YUM repos for Oracle Linux Cloud Native Environment =====
    worker2:     yum install -y jq
    worker2:     yum install -y yum-utils
    worker2:     yum install -y oracle-olcne-release-el7
    worker2:     yum-config-manager --disable ol7_olcne
    worker2:     yum-config-manager --enable ol7_olcne11
    worker2:     yum-config-manager --disable ol7_developer*
    worker2:     yum-config-manager --enable ol7_kvm_utils
    worker2: ===== Fulfil requirements =====
    worker2:     swapoff -a
    worker2:     sed -i '/ swap /d' /etc/fstab
    worker2:     modprobe br_netfilter
    worker2:     eval echo 'br_netfilter' > /etc/modules-load.d/br_netfilter.conf
    worker2:     /usr/sbin/setenforce 0
    worker2:     sed -i 's/^SELINUX=.*/SELINUX=permissive/g' /etc/selinux/config
    worker2:     systemctl enable --now firewalld
    worker2:     firewall-cmd --permanent --zone=public --add-interface=eth0
    worker2: ===== Installing the Oracle Linux Cloud Native Environment Platform Agent =====
    worker2:     yum install -y olcne-agent olcne-utils
    worker2:     yum install -y kubeadm kubelet kubectl

    worker2:     sysctl -p /etc/sysctl.d/k8s.conf
    worker2:     systemctl enable olcne-agent.service
    worker2:     firewall-cmd --zone=trusted --add-interface=cni0 --permanent
    worker2:     firewall-cmd --add-port=8090/tcp --permanent
    worker2:     firewall-cmd --add-port=10250/tcp --permanent
    worker2:     firewall-cmd --add-port=10255/tcp --permanent
    worker2:     firewall-cmd --add-port=8472/udp --permanent
    worker2:     firewall-cmd --add-port=30000-32767/tcp --permanent
    worker2:     systemctl restart firewalld
    worker2: ===== Allow passwordless ssh between VMs =====
    worker2:     mkdir /root/.ssh
    worker2:     cp /vagrant/id_rsa /root/.ssh/
    worker2:     cp /vagrant/id_rsa.pub /root/.ssh/authorized_keys
    worker2:     eval cat /vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    worker2:     chmod 0700 /root/.ssh
    worker2:     chmod 0600 /root/.ssh/authorized_keys /root/.ssh/id_rsa
    worker2: ===== Oracle Linux base software installation complete. =====
==> master1: Importing base box 'oraclelinux/7'...
==> master1: Matching MAC address for NAT networking...
==> master1: Checking if box 'oraclelinux/7' version '7.8.142' is up to date...
==> master1: Setting the name of the VM: OLCNE_master1_1605113556731_61632
==> master1: Fixed port collision for 22 => 2222. Now on port 2201.
==> master1: Clearing any previously set network interfaces...
==> master1: Preparing network interfaces based on configuration...
    master1: Adapter 1: nat
    master1: Adapter 2: hostonly
==> master1: Forwarding ports...
    master1: 22 (guest) => 2201 (host) (adapter 1)
==> master1: Running 'pre-boot' VM customizations...
==> master1: Booting VM...
==> master1: Waiting for machine to boot. This may take a few minutes...
    master1: SSH address: 127.0.0.1:2201
    master1: SSH username: vagrant
    master1: SSH auth method: private key
    master1:
    master1: Vagrant insecure key detected. Vagrant will automatically replace
    master1: this with a newly generated keypair for better security.
    master1:
    master1: Inserting generated public key within guest...
    master1: Removing insecure key from the guest if it's present...
    master1: Key inserted! Disconnecting and reconnecting using new SSH key...
==> master1: Machine booted and ready!
==> master1: Checking for guest additions in VM...
==> master1: Setting hostname...
==> master1: Mounting shared folders...
    master1: /vagrant => /home/rikuma/Downloads/vagrant-projects/OLCNE
==> master1: Running provisioner: shell...
    master1: Running: /tmp/vagrant-shell20201111-77286-6ut3kt.sh
    master1: ===== Configure private network =====
    master1:     ifup eth1
    master1: ===== Configure YUM repos for Oracle Linux Cloud Native Environment =====
    master1:     yum install -y jq
    master1:     yum install -y yum-utils
    master1:     yum install -y oracle-olcne-release-el7
    master1:     yum-config-manager --disable ol7_olcne
    master1:     yum-config-manager --enable ol7_olcne11
    master1:     yum-config-manager --disable ol7_developer*
    master1:     yum-config-manager --enable ol7_kvm_utils
    master1: ===== Fulfil requirements =====
    master1:     swapoff -a
    master1:     sed -i '/ swap /d' /etc/fstab
    master1:     modprobe br_netfilter
    master1:     eval echo 'br_netfilter' > /etc/modules-load.d/br_netfilter.conf
    master1:     /usr/sbin/setenforce 0
    master1:     sed -i 's/^SELINUX=.*/SELINUX=permissive/g' /etc/selinux/config
    master1:     systemctl enable --now firewalld
    master1:     firewall-cmd --permanent --zone=public --add-interface=eth0
    master1: ===== Installing the Oracle Linux Cloud Native Environment Platform API Server and Platform CLI tool to the operator node. =====
    master1:     yum install -y olcnectl olcne-api-server olcne-utils
    master1:     systemctl enable olcne-api-server.service
    master1:     firewall-cmd --add-port=8091/tcp --permanent
    master1:     firewall-cmd --add-masquerade --permanent
    master1: ===== Installing the Oracle Linux Cloud Native Environment Platform Agent =====
    master1:     yum install -y olcne-agent olcne-utils
    master1:     yum install -y kubeadm kubelet kubectl
    master1:     sysctl -p /etc/sysctl.d/k8s.conf
    master1:     systemctl enable olcne-agent.service
    master1:     firewall-cmd --zone=trusted --add-interface=cni0 --permanent
    master1:     firewall-cmd --add-port=8090/tcp --permanent
    master1:     firewall-cmd --add-port=10250/tcp --permanent
    master1:     firewall-cmd --add-port=10255/tcp --permanent
    master1:     firewall-cmd --add-port=8472/udp --permanent
    master1:     firewall-cmd --add-port=30000-32767/tcp --permanent
    master1:     yum install -y bash-completion
    master1:     firewall-cmd --add-port=6443/tcp --permanent
    master1:     firewall-cmd --add-port=8001/tcp --permanent
    master1:     systemctl enable kubectl-proxy.service
    master1:     firewall-cmd --add-port=10251/tcp --permanent
    master1:     firewall-cmd --add-port=10252/tcp --permanent
    master1:     firewall-cmd --add-port=2379/tcp --permanent
    master1:     firewall-cmd --add-port=2380/tcp --permanent
    master1:     firewall-cmd --add-port=6444/tcp --permanent
    master1:     firewall-cmd --add-protocol=vrrp --permanent
    master1:     podman pull container-registry.oracle.com/olcne/nginx:1.12.2
    master1:     systemctl restart firewalld
    master1: ===== Allow passwordless ssh between VMs =====
    master1:     mkdir /root/.ssh
    master1:     cp /vagrant/id_rsa /root/.ssh/
    master1:     cp /vagrant/id_rsa.pub /root/.ssh/authorized_keys
    master1:     eval cat /vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    master1:     chmod 0700 /root/.ssh
    master1:     chmod 0600 /root/.ssh/authorized_keys /root/.ssh/id_rsa
    master1: ===== Removing the shared SSH keypair =====
    master1:     rm /vagrant/id_rsa /vagrant/id_rsa.pub
    master1: ===== Oracle Linux base software installation complete. =====
    master1: ===== Generate and deploy X.509 Certificates =====
    master1:     /etc/olcne/gen-certs-helper.sh --nodes 192.168.99.101,192.168.99.111,192.168.99.112 --cert-dir /etc/olcne/pki
    master1:     sed -i -e 's/^USER=.*/USER=vagrant/' /etc/olcne/pki/olcne-tranfer-certs.sh
    master1:     bash -e /etc/olcne/pki/olcne-tranfer-certs.sh
    master1: ===== Bootstrap the Oracle Linux Cloud Native Environment Platform Agent on all nodes =====
    master1:     /etc/olcne/bootstrap-olcne.sh --secret-manager-type file --olcne-node-cert-path /etc/olcne/pki/production/node.cert --olcne-ca-path /etc/olcne/pki/production/ca.cert --olcne-node-key-path /etc/olcne/pki/production/node.key --olcne-component api-server
    master1:     ssh 192.168.99.101 /etc/olcne/bootstrap-olcne.sh --secret-manager-type file --olcne-node-cert-path /etc/olcne/pki/production/node.cert --olcne-ca-path /etc/olcne/pki/production/ca.cert --olcne-node-key-path /etc/olcne/pki/production/node.key --olcne-component agent
    master1:     ssh 192.168.99.111 /etc/olcne/bootstrap-olcne.sh --secret-manager-type file --olcne-node-cert-path /etc/olcne/pki/production/node.cert --olcne-ca-path /etc/olcne/pki/production/ca.cert --olcne-node-key-path /etc/olcne/pki/production/node.key --olcne-component agent
    master1:     ssh 192.168.99.112 /etc/olcne/bootstrap-olcne.sh --secret-manager-type file --olcne-node-cert-path /etc/olcne/pki/production/node.cert --olcne-ca-path /etc/olcne/pki/production/ca.cert --olcne-node-key-path /etc/olcne/pki/production/node.key --olcne-component agent
    master1: ===== Create the Oracle Linux Cloud Native Environment: olcne-env =====
    master1:     olcnectl --api-server 127.0.0.1:8091 environment create --environment-name olcne-env --secret-manager-type file --olcne-node-cert-path /etc/olcne/pki/production/node.cert --olcne-ca-path /etc/olcne/pki/production/ca.cert --olcne-node-key-path /etc/olcne/pki/production/node.key --update-config
    master1: ===== Create the Kubernetes module for olcne-env  =====
    master1:     olcnectl module create --environment-name olcne-env --module kubernetes --name olcne-cluster --container-registry container-registry.oracle.com/olcne --nginx-image container-registry.oracle.com/olcne/nginx:1.12.2 --apiserver-advertise-address 192.168.99.101 --virtual-ip 192.168.99.99 --master-nodes 192.168.99.101:8090 --worker-nodes 192.168.99.111:8090,192.168.99.112:8090
    master1: ===== Validate all required prerequisites are met for the Kubernetes module =====
    master1:     olcnectl module validate --environment-name olcne-env --name olcne-cluster
    master1: ===== Deploy the Kubernetes module into olcne-env (Be patient!) =====
    master1:     olcnectl module install --environment-name olcne-env --name olcne-cluster

    master1: Returned a non-zero code: 1
    master1: Last output lines:
    master1: Encountered errors with 192.168.99.101:8090
    master1:   Could not unmarshal JSON result for kubernetes-control-plane on 192.168.99.101:8090: invalid character 'd' after object key:value pair ({"error":"Timeout after 300 second when running: /usr/libexec/kubeman [set kubernetes-control-plane {"desired_state":"installing","kubernetes_version":"1.17.9-1","image_repository":"container-registry.oracle.com/olcne","apiserver_advertise_address":"192.168.99.101","apiserver_cert_extra_sans":"","service_cidr":"10.96.0.0/12","pod_cidr":"10.244.0.0/16","apiserver_bind_port":"6444","kube_proxy_mode":"iptables","load_balancer":"192.168.99.99:6443","token":"","pod_network":"flannel","is_primary":"true","is_master":"true","join_command":"","upload_certificate_key":"108010a298c7f1f9e005e97bd98d731a3efbc76f95853f77dbe26d9843855863","etcd_image_tag":"3.4.3-1","coredns_image_tag":"1.6.5-1","pod-network-iface":""}]", "user_action":[]})
    master1: See /var/tmp/cmd_szPYg.log for details
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Environment (please complete the following information):**

- Host OS: [e.g. Oracle Linux 8, macOS 10.14.6, Windows 10 Pro, ...] : RHEL 8.2
- Kernel version (for Linux host): [run `uname -a`] 4.18.0-193.6.3.el8_2.x86_64
- Vagrant version: [e.g. 2.2.9] Latest Version: 2.2.13
- Vagrant provider:
  - For VirtualBox:
    - VirtualBox version: [e.g. 6.1.8r137981 -- run `vboxmanage -v`] 6.1.10r138449
 - Vagrant project:  [e.g. OLCNE, OracleDatabase/19.3.0, ...] OLCNE

**Additional information**

Add any other information about the issue here (console log, ...).

**Comment by mark-au** [comment]
Thanks for all the detail. The timeout message can be due to slow access to the image registries. I'd suggest you use a more local mirror than the default and instructions are available at https://github.com/oracle/vagrant-projects/tree/master/OLCNE#repositories Are you using a proxy?

**Comment by rikumabokss** [comment]
Hi,
There are no proxy in this env. I have changed the registry URL to the near one me but still it fails with same error
Is there any way through which I can re run the provision part only ( after resolving the failure reason of packet download etc from the VM ) instead of going through all fresh installation if it fails any where.

**Comment by rikumabokss** [comment]
Hi,
I have been able to deploy it after creating a local registry and making changes in vagrant file for the same. 
Thanks
