### ISSUE TITLE
OLCNE : Services not coming up after Nodes Reboot

### ISSUE THREAD

**Issue by rikumabokss** [oracle/vagrant-projects#325]
**Describe the issue**
After the installation of OLCNE, when the nodes are rebooted, kubernetes is unale to come up

**Environment (please complete the following information):**

- Host OS: [e.g. Oracle Linux 8, macOS 10.14.6, Windows 10 Pro, ...] Oracle Linux Server release 7.8
- Kernel version (for Linux host): [run `uname -a`] 4.14.35-2025.400.8.el7uek.x86_64
- Vagrant version: [e.g. 2.2.9] 2.2.13
- Vagrant provider:
  - For VirtualBox:
    - VirtualBox version: [e.g. 6.1.8r137981 -- run `vboxmanage -v`] 6.1.10r138449
  - For libvirt:
    - Vagrant-libvirt plugin version: [e.g. 0.1.2 -- run `vagrant plugin list`]
    - QEMU and libvirt version:  
      If you have `virsh` installed run `virsh -c qemu:///system version --daemon`  
      Alternatively query your package manager with e.g.  
        `rpm -q qemu-kvm libvirt`,  
        `dpkg -l qemu-kvm libvirt\* | grep ^ii`, ...
- Vagrant project:  [e.g. OLCNE, OracleDatabase/19.3.0, ...] OLCNE

**Additional information**

kubelet logs on master node:
[root@master1 olcne]# systemctl status kubelet -l
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf, 90-node-ip.conf
   Active: active (running) since Wed 2020-11-18 16:16:08 UTC; 9min ago
     Docs: http://kubernetes.io/docs/
 Main PID: 4750 (kubelet)
   CGroup: /system.slice/kubelet.service
           └─4750 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --container-runtime=remote --container-runtime-endpoint=/var/run/crio/crio.sock --fail-swap-on=false --node-ip=192.168.99.101 --container-runtime=remote --container-runtime-endpoint=unix:///var/run/crio/crio.sock --runtime-request-timeout=10m

Nov 18 16:25:53 master1.vagrant.vm kubelet[4750]: E1118 16:25:53.333135    4750 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.CSIDriver: Get https://192.168.99.99:6443/apis/storage.k8s.io/v1beta1/csidrivers?limit=500&resourceVersion=0: EOF
Nov 18 16:25:53 master1.vagrant.vm kubelet[4750]: E1118 16:25:53.335503    4750 kubelet.go:2264] node "master1.vagrant.vm" not found
Nov 18 16:25:53 master1.vagrant.vm kubelet[4750]: E1118 16:25:53.436641    4750 kubelet.go:2264] node "master1.vagrant.vm" not found
Nov 18 16:25:53 master1.vagrant.vm kubelet[4750]: E1118 16:25:53.533239    4750 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/kubelet.go:458: Failed to list *v1.Node: Get https://192.168.99.99:6443/api/v1/nodes?fieldSelector=metadata.name%3Dmaster1.vagrant.vm&limit=500&resourceVersion=0: EOF
Nov 18 16:25:53 master1.vagrant.vm kubelet[4750]: E1118 16:25:53.536877    4750 kubelet.go:2264] node "master1.vagrant.vm" not found
Nov 18 16:25:53 master1.vagrant.vm kubelet[4750]: E1118 16:25:53.648796    4750 kubelet.go:2264] node "master1.vagrant.vm" not found
Nov 18 16:25:53 master1.vagrant.vm kubelet[4750]: E1118 16:25:53.740752    4750 controller.go:135] failed to ensure node lease exists, will retry in 7s, error: Get https://192.168.99.99:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/master1.vagrant.vm?timeout=10s: EOF
Nov 18 16:25:53 master1.vagrant.vm kubelet[4750]: E1118 16:25:53.748955    4750 kubelet.go:2264] node "master1.vagrant.vm" not found
Nov 18 16:25:53 master1.vagrant.vm kubelet[4750]: E1118 16:25:53.855213    4750 kubelet.go:2264] node "master1.vagrant.vm" not found
Nov 18 16:25:53 master1.vagrant.vm kubelet[4750]: E1118 16:25:53.934083    4750 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.RuntimeClass: Get https://192.168.99.99:6443/apis/node.k8s.io/v1beta1/runtimeclasses?limit=500&resourceVersion=0: EOF

kubelet logs on worker node:
.
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf, 90-node-ip.conf
   Active: active (running) since Wed 2020-11-18 16:08:34 UTC; 17min ago
     Docs: http://kubernetes.io/docs/
 Main PID: 1164 (kubelet)
   CGroup: /system.slice/kubelet.service
           └─1164 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --container-runtime=remote --container-runtime-endpoint=/var/run/crio/crio.sock --fail-swap-on=false --node-ip=192.168.99.111 --container-runtime=remote --container-runtime-endpoint=unix:///var/run/crio/crio.sock --runtime-request-timeout=10m

Nov 18 16:26:23 worker1.vagrant.vm kubelet[1164]: E1118 16:26:23.012120    1164 kubelet.go:2264] node "worker1.vagrant.vm" not found
Nov 18 16:26:23 worker1.vagrant.vm kubelet[1164]: E1118 16:26:23.117119    1164 kubelet.go:2264] node "worker1.vagrant.vm" not found
Nov 18 16:26:23 worker1.vagrant.vm kubelet[1164]: E1118 16:26:23.218141    1164 kubelet.go:2264] node "worker1.vagrant.vm" not found
Nov 18 16:26:23 worker1.vagrant.vm kubelet[1164]: E1118 16:26:23.318477    1164 kubelet.go:2264] node "worker1.vagrant.vm" not found
Nov 18 16:26:23 worker1.vagrant.vm kubelet[1164]: E1118 16:26:23.365004    1164 file_linux.go:60] Unable to read config path "/etc/kubernetes/manifests": path does not exist, ignoring
Nov 18 16:26:23 worker1.vagrant.vm kubelet[1164]: E1118 16:26:23.435844    1164 kubelet.go:2264] node "worker1.vagrant.vm" not found
Nov 18 16:26:23 worker1.vagrant.vm kubelet[1164]: E1118 16:26:23.558777    1164 kubelet.go:2264] node "worker1.vagrant.vm" not found
Nov 18 16:26:23 worker1.vagrant.vm kubelet[1164]: E1118 16:26:23.754592    1164 kubelet.go:2264] node "worker1.vagrant.vm" not found
Nov 18 16:26:23 worker1.vagrant.vm kubelet[1164]: E1118 16:26:23.854812    1164 kubelet.go:2264] node "worker1.vagrant.vm" not found
Nov 18 16:26:23 worker1.vagrant.vm kubelet[1164]: E1118 16:26:23.955084    1164 kubelet.go:2264] node "worker1.vagrant.vm" not found

**Comment by mark-au** [comment]
Using a single master node does not give etcd a method of validating the leader but if there has only ever been one node I thought it would reconcile. 
I couldn't reproduce this problem, I did a `vagrant up`, waited for deployment, `vagrant halt` and then `vagrant up` and was soon able to run `kubectl get nodes` from master1. 

Can you show the etcd logs on the master?
`sudo crictl ps | grep etcd`
`sudo crictl logs CONTAINERID`

**Comment by rikumabokss** [comment]
Hi,
Thanks for the revert. Earlier I was not using "vagrant-hosts" plugin. After the setup and node reboot I can see that hostname are not correctly mapped. 
I have now enabled this plugin and running the setup again. 

Can you please share from your env which all vagrant plugin are enabled.

**Comment by rikumabokss** [comment]
Hi,
I can confirm that after enabling the "vagrant-hosts" plugin and doing a fresh restart the issue does not appear after the reboot of nodes. 
Probably vagrant-hosts plugin should be mentioned as mandatory in the install step.
Closing this case
Thanks
