### ISSUE TITLE
Kubernetes plugin in the Grafana

### ISSUE THREAD

**Issue by rikumabokss** [oracle/vagrant-projects#328]
**Describe the issue**

I have installed lates OLCNE with istio module and it has given me a grafana setup which lists out istio metrices in dashboard.

I also want to use this same Grafana for kubernetes graphs also. Although there is option of adding new dashboard and select from multiple query to have different kubernetes dashboard but it is long and process and dahsboards are not as well orgainzed as it is given in for this plugin - https://grafana.com/grafana/plugins/grafana-kubernetes-app/installation

I am exploring how to install this plugin in the existing grafana setup of OLCNE.

**Comment by Djelibeybi** [comment]
This is not supported with the existing embedded instance of Grafana, which is only for use with Istio. Also, this repo is not for general support of OLCNE, but rather for issues with the deployment of OLCNE using Vagrant. Please use official support channels for general OLCNE-related questions.
