### ISSUE TITLE
Oracle Linux 8 putty install

### ISSUE THREAD

**Issue by harvybob** [oracle/vagrant-projects#331]
**Describe the issue**

Taking a fresh Oracle Linux 8 vagrant box - no changes to config.
I want to generate my own ssh key to use ssh outside of the command line - and as part of that i need to generate a .ppk key.
Normally i would use puttygen but i can not seem to install it - are there any work arounds?
.

If i try to install it i get not found, 
```
[root@ol8-vagrant .ssh]# yum install puttygen
Last metadata expiration check: 0:12:51 ago on Wed 25 Nov 2020 12:25:30 PM UTC.
No match for argument: puttygen
Error: Unable to find a match: puttygen
```

**Environment (please complete the following information):**

- Host OS: [e.g. Oracle Linux 8, macOS 10.14.6, Windows 10 Pro, ...] Windows 10 pro
- Kernel version (for Linux host): [run `uname -a`]  Linux ol8-vagrant 5.4.17-2036.100.6.1.el8uek.x86_64 #2 SMP Thu Oct 29 17:06:00 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
- Vagrant version: [e.g. 2.2.9] Vagrant 2.2.13
- Vagrant provider:
  - For VirtualBox:  6.1.16 r140961
    - VirtualBox version: [e.g. 6.1.8r137981 -- run `vboxmanage -v`]  6.1.16 r140961

- Vagrant project:  [e.g. OLCNE, OracleDatabase/19.3.0, ...]
OracleLinux\8\

**Additional information**
May generally not be available for Linux 8? is there something else i can use?
Add any other information about the issue here (console log, ...).

When i tried to generate the ppk:
```[vagrant@ol8-vagrant .ssh]$ puttygen id_rsa -o id_rsa.ppk
-bash: puttygen: command not found

``

I've checked in the OL8 repo and putty and puttygen are not there.
When i did it on OracleDatabase\12.2\ putty installed - with linux version
```Linux oracle-12201-vagrant 5.4.17-2036.100.6.1.el7uek.x86_64 #2 SMP Thu Oct 29 17:04:48 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by PaulNeumann** [comment]
@harvybob As far as I can tell, putty isn't available in either Oracle's or Red Hat's EPEL 8 repository. However, you can install it from either the Oracle or the Red Hat EPEL 7 repository.

To install from the Oracle EPEL 7 repository:

```bash
sudo dnf install https://yum.oracle.com/repo/OracleLinux/OL7/developer_EPEL/x86_64/getPackage/putty-0.73-1.el7.x86_64.rpm
```

To install from the Red Hat EPEL 7 repository:

```bash
sudo dnf install https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/putty-0.74-1.el7.x86_64.rpm
```

I hope this helps.

**Comment by AmedeeBulle** [comment]
@PaulNeumann, it is usually not a great idea to use a repo from another version as it will typically generate dependencies nightmares...

@harvybob  I am not sure why you would need `putty` on the Linux VM...
I assume you want to connect to your VM using `putty` on your Windows host.
In that case you need to generate an ssh key pair (with `puttygen`) on Windows, and copy the public key into the `authorized_keys` file of the user in the VM.

**Comment by harvybob** [comment]
@AmedeeBulle 
It was to create a key to allow mobxterm (a utility similar to putty) from my windows host
I will give your suggestion a go.

**Comment by PaulNeumann** [comment]
@AmedeeBulle Yes. Thank you for posting the warning and suggesting an alternative.

**Comment by Djelibeybi** [comment]
FYI, the `ssh-keygen` tool is installed by default and can create public/private key pairs that are usable by any SSH client, including MobaXterm.
