### ISSUE TITLE
Maybe - Update Readme for MacOS

### ISSUE THREAD

**Issue by jochen-halwachs** [oracle/vagrant-projects#332]
**Vagrant Libvirt installation on MacOS - using brew**

```bash
brew install vagrant-env
brew install libiconv gcc libvirt
vagrant plugin install vagrant-libvirt
```

**Environment (please complete the following information):**

- Host OS: macOS 20.1.0 Darwin Kernel Version 20.1.0
- Kernel version (for Linux host): see above
- Vagrant version: 2.2.14
- Vagrant provider:
  - For VirtualBox:
    - VirtualBox version: 6.1.16 r140961
  - For libvirt:
    - Vagrant-libvirt plugin version: vagrant-libvirt (0.3.0, global)
    - QEMU and libvirt version:  6.9.1
- Vagrant project: OracleDatabase/19.3.0

**Additional information**

ERROR: Failed to build gem native extension

**Comment by AmedeeBulle** [comment]
That won't work...

Although technically there is a Libvirt library for macOS, the image is a KVM image which will only run on Linux/KVM.

**Comment by jochen-halwachs** [comment]
Thank for your feedback - it works.

**Comment by AmedeeBulle** [comment]
Hi!

Not sure what you exactly mean by "it works"...

To clarify my statement above, the purpose of the Libvirt boxes is to offer an alternative to the VirtualBox provider on Linux to get the benefits of the KVM virtualization on Linux (virtio modules).
We are only testing the Libvirt boxes on Linux.

Having said that they most probably run as well with `qemu-system-x86_64` on any platform -- not sure though if there is any benefits to use these compared to the VirtualBox ones.

Now as your issue mentions, the pain will probably be in building the `vagrant-libvirt` plugin with the various dependencies to the Ruby Gems (you definitely need to make sure the macOS SSL libraries are out of the way).

If you have a working configuration, I am happy to advertise it, but I do not have resources to investigate this myself for the time being.

Thanks.
