### ISSUE TITLE
Update Oracle Database download instructions and filenames

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-projects#333]
The installation zip files for Oracle Database 12.1.0.2, 12.2.0.1 and 18.3.0 are no longer available for download from OTN.  They _are_ available from [Oracle Software Delivery Cloud](https://edelivery.oracle.com/), but the filenames are different.

You can work around this issue by downloading the appropriate files from [Oracle Software Delivery Cloud](https://edelivery.oracle.com/), then renaming the downloaded files to match the old OTN filenames before running `vagrant up`.

| Database Version | New Filename(s) | Old OTN Filename(s) |
|---|---|---|
| 12.1.0.2 Enterprise Edition | `V46095-01_1of2.zip` AND `V46095-01_2of2.zip` | `linuxamd64_12102_database_1of2.zip` AND `linuxamd64_12102_database_2of2.zip` |
| 12.1.0.2 Standard Edition 2 | `V77388-01_1of2.zip` AND `V77388-01_2of2.zip` | `linuxamd64_12102_database_se2_1of2.zip` AND `linuxamd64_12102_database_se2_2of2.zip` |
| 12.2.0.1 | `V839960-01.zip` | `linuxx64_12201_database.zip` |
| 18.3.0 | `V978967-01.zip` | `LINUX.X64_180000_db_home.zip` |

I suggest updating the `README.md` files for the OracleDatabase/12.1.0.2, OracleDatabase/12.2.0.1, OracleDatabase/18.3.0, and OracleGoldenGate/12.2.0.1 projects to reflect the new download location and filenames, and updating the `install.sh` scripts to work with both the new filenames and the old OTN filenames.

If you agree that this is a legitimate issue, and that the proposed approach is correct, I'd be happy to work on it and submit a PR.

**Comment by gvenzl** [comment]
Hi Paul,

The zip files have been removed from OTN because these releases are soon to go out of premier support.
I don't think it warrants changing the vagrant files themselves nor the ReadMe as users soon should only be using 19c going forward.

If, for whatever reasons, users can and do download the older releases from Software Delivery Cloud they have a simple workaround by just renaming the zip file themselves.

**Comment by PaulNeumann** [comment]
@gvenzl It makes sense to stop maintaining the older releases, and I'm fine with whatever you decide.

My concern is that the READMEs now contain outdated information with no indication that it's inaccurate. Maybe it would help to create a new directory, say OracleDatabaseArchive, move the 12.1.0.2, 12.2.0.1 and 18.3.0 projects to that directory, and add a README saying that the projects in this directory are no longer maintained.

**Comment by gvenzl** [comment]
Hi @PaulNeumann, I agree that we should inform users whether/what is no longer maintained. Not sure yet whether a new folder is the right approach though and how or whether we want to keep the same behavior across different repositories. Something we need to think about more.

For now, I'm going to close this issue and perhaps open another ER once we know more.
