### ISSUE TITLE
RAC with 12.2 database and gi?

### ISSUE THREAD

**Issue by harvybob** [oracle/vagrant-projects#339]
Hi, I'm trying to setup a 12.2 RAC, but wanted to confirm file names I should put in the software folder?
When setting up 19c RAC the files were named as LINUX.X64_193000_db_home.zip and  LINUX.X64_193000_grid_home.zip

for 12.2 downloads the files are named linuxx64_12201_database.zip and linuxx64_12201_grid_home.zip
Do i need to rename the files, or do i need to make changes to the vagrant file to allow it to work?

If i leave everything as is and start up i get:

```Detected virtualbox
--------------------
ERROR: gi_software does not exist
```

A clear and concise description of what the issue is.  
Nothing as yet - also are any other changes needed to allow the 12c RAC environment to be stood up?

**Environment (please complete the following information):**

- Host OS: [e.g. Oracle Linux 8, macOS 10.14.6, Windows 10 Pro, ...] Windows 10 pro
- Kernel version (for Linux host): [run `uname -a`]
- Vagrant version: [e.g. 2.2.9]  2.2.13
- Vagrant provider:
  - For VirtualBox:6.1.16 r140961

- Vagrant project:  [e.g. OLCNE, OracleDatabase/19.3.0, ...]
vagrant-projects/OracleRAC/

**Additional information**

Just want to check what steps are needed to start up a 12.2 RAC setup - the notes are based on 19

**Comment by rcitton** [comment]
From https://edelivery.oracle.com you get
.
	V840012-01.zip	Oracle Database Grid Infrastructure 12.2.0.1.0 for Linux x86-64, 2.8 GB
	V839960-01.zip	Oracle Database 12.2.0.1.0 for Linux x86-64, 3.2 GB
.
then you should move them as
    mv V840012-01.zip   <path>/ORCL_software/LINUX.X64_122010_grid_home.zip
    mv V839960-01.zip   <path>/ORCL_software/LINUX.X64_122010_db_home.zip

and change "vagrant.yml" conf file according with file name LINUX.X64_122010_xxx.zip

**Comment by harvybob** [comment]
I've made changes to the following files:
config/setup.env
config/vagrant.yml
scripts/09_gi_installation.sh
scripts/11_gi_config.sh
scripts/13_RDBMS_software_installation.sh
scripts/14_create_database.sh

The scripts files all had paths that needed to be ammended from 19 to 12. Its starting up now so will feed back any issues once its up.

**Comment by rcitton** [comment]
Please follow my comment above, you dont need to make any changes to sh file

**Comment by harvybob** [comment]
Apologies - I changed them as I want to go through the steps for updating grid to 19c and installing 19c database side by side so wanted naming correct.

Its stood up and working correctly - thanks for your assisstance!

**Comment by rcitton** [comment]
no prb, please close this issue request.
