### ISSUE TITLE
vagrant up timeout while provisioning 19.3 Database (virtualbox on OCI)

### ISSUE THREAD

**Issue by XiaoYu-HN** [oracle/vagrant-projects#341]
I have launched a linux 7 instance in OCI, with Vagrant and VirtualBox installed:

```
$ vagrant --version
Vagrant 2.2.14
$ vboxmanage --version
6.1.18r142142
```
but it failed while provisioning new 19.3 database:
```
$ pwd
/home/opc/vagrant-projects/OracleDatabase/19.3.0

$ time vagrant up
Bringing machine 'oracle-19c-vagrant' up with 'virtualbox' provider...
==> oracle-19c-vagrant: Importing base box 'oraclelinux/7'...
==> oracle-19c-vagrant: Matching MAC address for NAT networking...
==> oracle-19c-vagrant: Checking if box 'oraclelinux/7' version '7.9.184' is up to date...
==> oracle-19c-vagrant: Setting the name of the VM: oracle-19c-vagrant
==> oracle-19c-vagrant: Clearing any previously set network interfaces...
==> oracle-19c-vagrant: Preparing network interfaces based on configuration...
    oracle-19c-vagrant: Adapter 1: nat
==> oracle-19c-vagrant: Forwarding ports...
    oracle-19c-vagrant: 1521 (guest) => 1521 (host) (adapter 1)
    oracle-19c-vagrant: 5500 (guest) => 5500 (host) (adapter 1)
    oracle-19c-vagrant: 22 (guest) => 2222 (host) (adapter 1)
==> oracle-19c-vagrant: Running 'pre-boot' VM customizations...
==> oracle-19c-vagrant: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "1ac8b3f9-45cb-4f16-bcd8-ef316af8f135", "--type", "gui"]

Stderr: VBoxManage: error: The virtual machine 'oracle-19c-vagrant' has terminated unexpectedly during startup because of signal 6
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine


real    0m42.335s
user    0m3.634s
sys     0m3.459s

```

**Environment (please complete the following information):**

- Host OS: Oracle Linux Server 7.9
- Kernel version (for Linux host): Linux dbim-si-315405 5.4.17-2036.102.0.2.el7uek.x86_64 #2 SMP Tue Jan 5 12:41:34 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
- Vagrant version: 2.2.14
- Vagrant provider:
  - For VirtualBox:
    - VirtualBox version: 6.1.18r142142
- Vagrant project:  [OracleDatabase/19.3.0]

**Additional information**

the host is a compute instance in OCI, only 19.3 Single Instance failed at provisioning. RAC and DG vagrant box works fine.

**Comment by AmedeeBulle** [comment]
Hi!

You are getting this error because Vagrant attempt to start the VM with a GUI (`startvm --type gui`) and you most probably don't have an X server running in OCI.

Now I am not sure why we have this; to my knowledge none of our projects are currently enabling the gui option in the Vagrantfile.

Did you made any change to the project?

**Comment by XiaoYu-HN** [comment]
Sorry I have paste the wrong output. after stuck error, I have tried --type gui in Vagrantfile, but still failed. the actual error is as below:
```
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

BTW, I have create a new instance to reproduce the error, but this time all os OK.

**Comment by AmedeeBulle** [comment]
At this stage, Vagrant only asks VirtualBox to start a VM from the base box image, which is the same for all Database projects, and it will timeout if the VM is not up after 5 minutes.

It was most probably a transient issue with VirtualBox on your system, and there isn't a lot we can do from the Vagrant side...

If you still get this, you might want to add

```ruby
vb.customize ["modifyvm", :id, "--x2apic", "off"]
```

in the project Vagrantfile (or in your default vagrant config)

X2APIC sometimes gives issues in nested virtualization.
