### ISSUE TITLE
OLCNE: Oracle Linux 8 image doesn't have /dev/sdb

### ISSUE THREAD

**Issue by rafabene** [oracle/vagrant-projects#344]
**Describe the issue**

The Oracle Linux 8 image for OLCNE doesn't bring /dev/sdb.

The /dev/sdb device is needed to make the Gluster volume works when porting the lab https://oracle.github.io/linux-labs/OLCNE-Gluster/ to the latest version of the vagrant files.

**Comment by AmedeeBulle** [comment]
None of our base boxes still have an additional disk (`/dev/sdb`).

This has been removed quite some time ago, as there is little benefit to carry and extra disk image in the VirtualBox package and that feature wasn't available for the libvirt boxes.

If you need an extra disk for your project you can easily add it to your Vagrantfile, like we do for the [DockerEngine](https://github.com/oracle/vagrant-projects/blob/main/DockerEngine/Vagrantfile#L73-L82) project.

**Comment by rafabene** [comment]
Thanks for the explanation @AmedeeBulle 

Shouldn't we make the extra disk optional in the Vagrantfile of OLCNE and update the instruction of OLCNE-Gluster lab?

**Comment by Djelibeybi** [comment]
To be honest, I had forgotten about the Gluster lab. I'm not sure if @mark-au has any spare cycles for this update, and I don't have any myself for at least a week, so I'll say, "pull requests welcome!" until I get some spare time to fix it myself.

**Comment by AmedeeBulle** [comment]
I pinged @mark-au re. this lab when I did this change, and he was OK with the disk removal :)
AFAIK it is the only project which needs this; the easy path is to add a note to the lab...
... but PR welcome

**Comment by rafabene** [comment]
I'm willing to help with the PR but before starting working on it I'd like to perform an alignment. 

1) Is it preferable to have the creation of the extra disk as an optional parameter of OLCNE Vagrantfile?

2) Add a step in the lab to modify the existing OLCNE Vagrantfile. This is more error prone in my opinion.

My vote is for 1.

**Comment by Djelibeybi** [comment]
1 is fine with me.
