### ISSUE TITLE
Can I specify which point release of linux to use?

### ISSUE THREAD

**Issue by harvybob** [oracle/vagrant-projects#346]
**Describe the issue**

I want to know if I can specify the point release of Linux to use as the base to build the OracleRAC image?

**Environment (please complete the following information):**

- Host OS: [e.g. Oracle Linux 8, macOS 10.14.6, Windows 10 Pro, ...]
Win10pro
- Kernel version (for Linux host): [run `uname -a`]
- Vagrant version: [e.g. 2.2.9]
2.2.13
- Vagrant provider:
  - For VirtualBox:
    - VirtualBox version: 6.1.16r140961
  - For libvirt:
    - Vagrant-libvirt plugin version: [e.g. 0.1.2 -- run `vagrant plugin list`]
    - QEMU and libvirt version:  
      If you have `virsh` installed run `virsh -c qemu:///system version --daemon`  
      Alternatively query your package manager with e.g.  
        `rpm -q qemu-kvm libvirt`,  
        `dpkg -l qemu-kvm libvirt\* | grep ^ii`, ...
- Vagrant project:  [e.g. OLCNE, OracleDatabase/19.3.0, ...]
OracleRAC (but not specific i guess!)

**Additional information**
I'm looking to mimic an existing environment for upgrade testing, the current env is using RHEL 7.8 kernal 3.10.0-1127.
Is there a way I can set my vagrant built to use the equivalent Oracle Linux build?

Add any other information about the issue here (console log, ...).

**Comment by totalamateurhour** [comment]
Can you clarify what you are trying to achieve and which Vagrantfile/project you are using in this repo?

**Comment by harvybob** [comment]
> Can you clarify what you are trying to achieve and which Vagrantfile/project you are using in this repo?

Apologies - I pressed enter before completing the template. I've updated it now.

**Comment by totalamateurhour** [comment]
> I'm looking to mimic an existing environment for upgrade testing, the current env is using RHEL 7.8 kernal 3.10.0-1127.
> Is there a way I can set my vagrant built to use the equivalent Oracle Linux build?

While you could alter the Vagrantfile to use an earlier update of Oracle Linux, based on [this metadata](https://github.com/oracle/vagrant-projects/blob/gh-pages/boxes/oraclelinux/7.json), you'd be missing important security fixes.  Also, all projects in this repo use boxes built with the Unbreakable Enterprise Kernel (currently, 5.4.17)
