### ISSUE TITLE
How do I connect to SQL DEVELOPER from this vagrant box on my windows laptop?

### ISSUE THREAD

**Issue by sugamkarki** [oracle/vagrant-projects#354]

**Comment by PaulNeumann** [comment]
@sugamkarki If you're running one of the single instance database projects (e.g., 18.4.0-XE or 19.3.0), the connection parameters are shown in the __Connecting to Oracle__ section of the project's `README.md`. For example, to connect to the 19.3.0 PDB, the parameters would be:

- Hostname: localhost
- Port: 1521
- Service name: ORCLPDB1

Here's what that looks like in SQL Developer:

![image](https://user-images.githubusercontent.com/38871902/112034852-902e1000-8b04-11eb-9686-2d718f12e0ee.png)

If you want to connect to the CDB instead, the Service name is __ORCLCDB.__  For the 18.4.0-XE project, the Service name for the CDB is __XE__, and the Service name for the PDB is __XEPDB1__.

The database passwords for the SYS, SYSTEM and PDBADMIN accounts are shown at the end of the output from `vagrant up`.

I hope this helps.
