### ISSUE TITLE
No MySQL for LAMP

### ISSUE THREAD

**Issue by pguerin3** [oracle/vagrant-projects#358]
**MySQL install is missing**

I can clone vagrant_boxes, and vagrant up works first time in the LAMP directory.
There are no issues doing a vagrant ssh to login.
Seems there is just a Linux 7 VM and nothing else.
Is there supposed to be a MySQL db pre-installed as a component of the LAMP stack?

**Environment:**

- Host OS: Windows 10
- Kernel version (for Linux host):
Linux ol7-lamp 5.4.17-2036.102.0.2.el7uek.x86_64 #2 SMP Tue Jan 5 12:41:34 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
- Vagrant project:
\vagrant-boxes\LAMP

**Comment by PaulNeumann** [comment]
@pguerin3 This may be a problem with symbolic links. Apache, MySQL and PHP are installed by the script `vagrant-projects/LAMP/scripts/lamp.sh`, which is really a symbolic link to the script `vagrant-projects/OracleLinux/7/scripts/lamp.sh`. Unless Windows and Git for Windows are configured to work with symbolic links, the script doesn't run.

Getting symbolic links working on Windows can be tricky. There's some good information in [the Git for Windows documentation](https://github.com/git-for-windows/git/wiki/Symbolic-Links) and [this blog post by Josh Kelley](https://www.joshkel.com/2018/01/18/symlinks-in-windows/).

If you'd prefer not to configure Windows and Git for Windows to use symbolic links, you can just replace the file `lamp.sh` in  the `vagrant-projects/LAMP/scripts` directory with the one from the `vagrant-projects/OracleLinux/7/scripts` directory. When you rebuild the VM (`vagrant destroy`, then `vagrant up`), Apache, MySQL and PHP should be installed.

I hope this helps.

**Comment by AmedeeBulle** [comment]
Thanks for you insight on this issue @PaulNeumann. I need to plead guilty as I don't have a Windows environment to test.

An alternative solution is to use the `OracleLinux/7` project and _extend_ it with the `lamp` extension -- this is documented in the [OL7 project README](https://github.com/oracle/vagrant-projects/tree/main/OracleLinux/7#extending-the-project) file.

(The LAMP project is actually deprecated in favor of the extension, as we wanted to avoid to create too many "simple" projects at the top level)

**Comment by PaulNeumann** [comment]
@AmedeeBulle Thank you. Extending the OracleLinux/7 project with the lamp extension is a better alternative. I should have remembered why the symlink exists in the first place.

Would it help to add notes to the README files for the ContainerTools, DockerEngine and LAMP projects stating that they're deprecated and recommending the use of the appropriate OracleLinux project instead?

**Comment by AmedeeBulle** [comment]
> Would it help to add notes to the README files for the ContainerTools, DockerEngine and LAMP projects stating that they're deprecated and recommending the use of the appropriate OracleLinux project instead?

PR welcome ;)
