### ISSUE TITLE
unzip: cannot find or open

### ISSUE THREAD

**Issue by pguerin3** [oracle/vagrant-projects#360]
**Describe the issue**

I get the following error when I vagrant up:

``
    oracle-19c-vagrant: INSTALLER: Oracle preinstall and openssl complete
    oracle-19c-vagrant: INSTALLER: Oracle directories created
    oracle-19c-vagrant: INSTALLER: Environment variables set
    oracle-19c-vagrant: unzip:  cannot find or open /vagrant/LINUX.X64_193000_db_home.zip, /vagrant/LINUX.X64_193000_db_home.zip.zip or /vagrant/LINUX.X64_193000_db_home.zip.ZIP.
``

I can login into the Linux environment, but can't access the database.

**Environment (please complete the following information):**

- Host OS: ``Windows 10``
- Kernel version (for Linux host):
``Linux oracle-19c-vagrant 5.4.17-2036.102.0.2.el7uek.x86_64 #2 SMP Tue Jan 5 12:41:34 PST 2021 x86_64 x86_64 x86_64 GNU/Linux``
- Vagrant provider:
  - For VirtualBox:
    - VirtualBox version: ``6.1.18r142142``
- Vagrant project: ``vagrant-boxes\OracleDatabase\19.3.0``

**Comment by PaulNeumann** [comment]
@pguerin3 You need to download the database installation zip file (`LINUX.X64_193000_db_home.zip`) into the `vagrant-projects/OracleDatabase/19.3.0` directory before running `vagrant up`. Please see the [Getting started](https://github.com/oracle/vagrant-projects/blob/main/OracleDatabase/19.3.0/README.md#getting-started) section of the project's [README.md](https://github.com/oracle/vagrant-projects/blob/main/OracleDatabase/19.3.0/README.md) file for more information.

I hope this helps.
