### ISSUE TITLE
DB projects - install.sh oratab issue

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-projects#370]
The `install.sh` scripts for the 19.3.0, 18.3.0, 12.2.0.1, and 12.1.0.2 single-instance database projects use the following code to modify the last line of the oratab file so that dbstart starts the database at boot time:

```bash
sed '$s/N/Y/' /etc/oratab | sudo tee /etc/oratab > /dev/null
```

The last line of the oratab file uses the format `$ORACLE_SID:$ORACLE_HOME:<N|Y>`. With the default SID name and ORACLE_HOME directory, it's `ORCLCDB:/opt/oracle/product/19c/dbhome_1:N` before modification.

The intent of the `sed` command is to change the third field in the last line of the file from "N" to "Y". This works fine with the default SID name and ORACLE_HOME directory, but both of these are configurable, so they might contain "N" characters. The command changes the first "N" found in the last line, which may not be the correct one.

It would be safer to use one of the following commands to replace only the "N" character at the end of the line:

```bash
# short and simple
sed -i -e '$s/N$/Y/' /etc/oratab

# longer, but maybe clearer
sed -i -e "\$s|${ORACLE_SID}:${ORACLE_HOME}:N|${ORACLE_SID}:${ORACLE_HOME}:Y|" /etc/oratab
```

Both options work correctly, and both modify the file in place, making the code cleaner.

If you agree that this is a legitimate issue, and that the suggested change makes sense, I'd be happy to submit a PR.

**Comment by gvenzl** [comment]
Hi @PaulNeumann,

Yes, the issue is legitimate, please submit a PR! 👍🏻
