### ISSUE TITLE
Oracle Database 21c

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-projects#374]
Congratulations on the on-prem release of Oracle Database 21c!

I couldn't resist working on a 21c Vagrant build, based on the 19.3.0 project in this repository. (You can see it [here](https://github.com/PaulNeumann/vagrant-test/tree/main/OracleDatabase/21.3.0)).

I wanted to share a few things I found, in case they help someone else:

- Either Oracle Linux 7 or Oracle Linux 8 will work, but Oracle Linux 8 seems to be a little faster.
- At least 2.5 GB of VM memory is required to avoid warnings from DBCA.
- ~~The 21c preinstallation RPM isn't available yet, but the 19c preinstallation RPM seems to work. (Probably not a good idea for a real install, though.)~~ Edit 16-Aug-2021: The 21c preinstallation RPM is now available.
- Unlike 19c, the 21c runInstaller script returns an exit status of 6 (successful with warnings) when prerequisite failures are ignored.
- In 21c, read-only Oracle homes are the default (documentation is [here](https://docs.oracle.com/en/database/oracle/oracle-database/21/rilin/about-read-only-oracle-home.html#GUID-D848002A-DBAD-48FA-8467-E849630B8E42)). Among other things, this changes the location of the sqlnet.ora, listener.ora and tnsnames.ora files.

I hope this helps. Again, congratulations on the release.

**Comment by AmedeeBulle** [comment]
Apologies for not responding earlier...

A pull request is always appreciated ;)
