### ISSUE TITLE
Grid is not setup correctly

### ISSUE THREAD

**Issue by faguirre154** [oracle/vagrant-projects#375]
**Grid is not set up correctly**

Vagrant up aborted with SYSTEM_THREAD_EXCEPTION_NOT_HANDLED with nvlddmkm.sys

**Environment (please complete the following information):**

- Host OS: Windows 10 Home Single Language
- Kernel version (for Linux host): Linux node1 5.4.17-2036.100.6.1.el7uek.x86_64 #2 SMP Thu Oct 29 17:04:48 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
- Vagrant version: Installed Version: 2.2.9
- Vagrant provider:
  - For VirtualBox:
    - VirtualBox version: 6.1.16r140961
  - For libvirt:
    - Vagrant-libvirt plugin version: [e.g. 0.1.2 -- run `vagrant plugin list`]
    - QEMU and libvirt version:  
      If you have `virsh` installed run `virsh -c qemu:///system version --daemon`  
      Alternatively query your package manager with e.g.  
        `rpm -q qemu-kvm libvirt`,  
        `dpkg -l qemu-kvm libvirt\* | grep ^ii`, ...
- Vagrant project:  OracleRAC/19.3.0

**Additional information**

Running vagrant-shell as root (/tmp/vagrant-shell), failed with below error:

-----------------------------------------------------------------
INFO: 2021-08-24 18:52:00: Setup /etc/hosts
-----------------------------------------------------------------
-----------------------------------------------------------------
INFO: 2021-08-24 18:52:00: Setup SCAN on /etc/hosts
-----------------------------------------------------------------
-----------------------------------------------------------------
INFO: 2021-08-24 18:52:00: Setup /etc/resolv.conf
-----------------------------------------------------------------
-----------------------------------------------------------------
INFO: 2021-08-24 18:52:00: Setup chronyd service
-----------------------------------------------------------------
200 OK
-----------------------------------------------------------------
INFO: 2021-08-24 18:52:00: Setting-up shared disks partions
-----------------------------------------------------------------
Not supported provider:
-----------------------------------------------------------------
INFO: 2021-08-24 18:52:00: Setup oracle and grid user
-----------------------------------------------------------------
groupdel: cannot remove the primary group of user 'grid'
groupadd: group 'oinstall' already exists
groupadd: group 'dbaoper' already exists
groupadd: group 'asmadmin' already exists
groupadd: group 'asmoper' already exists
groupadd: group 'asmdba' already exists
useradd: user 'grid' already exists
-----------------------------------------------------------------
INFO: 2021-08-24 18:52:00: Set oracle and grid limits
-----------------------------------------------------------------
-----------------------------------------------------------------
INFO: 2021-08-24 18:52:00: Create GI_HOME and DB_HOME directories
-----------------------------------------------------------------
-----------------------------------------------------------------
INFO: 2021-08-24 18:52:01: Set user env
-----------------------------------------------------------------
-----------------------------------------------------------------
INFO: 2021-08-24 18:52:01: Set root, oracle and grid password
-----------------------------------------------------------------
Changing password for user root.
passwd: Authentication token manipulation error
Changing password for user grid.
passwd: Authentication token manipulation error
Changing password for user oracle.
passwd: Authentication token manipulation error
/tmp/vagrant-shell: line 659: [: node1: unary operator expected
-----------------------------------------------------------------
INFO: 2021-08-24 18:52:06: ASMLib disks label setup
-----------------------------------------------------------------
Not supported provider:
/tmp/vagrant-shell: line 717: [: node1: unary operator expected
-----------------------------------------------------------------
INFO: 2021-08-24 18:52:06: Running user-defined post-setup scripts
-----------------------------------------------------------------

**Comment by rcitton** [comment]
inside vagrant projet folder you should run "vagrant up" , not sure what is /tmp/vagrant-shell

**Comment by faguirre154** [comment]
C:\Users\Francisco\Downloads\vagrant-projects\OracleRAC>vagrant up

│▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│
 Oracle RAC (Real Application Cluster) Vagrant box for KVM/libVirt or VirtualBox
 Copyright (c) 1982-2020 Oracle and/or its affiliates
----------------------------------------------------------------------------------
 Author: Ruggero Citton <ruggero.citton@oracle.com>
         RAC Pack, Cloud Innovation and Solution Engineering Team
│▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│


--------------------
Detected virtualbox
--------------------
getting Proxy Configuration from Host...
Bringing machine 'node2' up with 'virtualbox' provider...
Bringing machine 'node1' up with 'virtualbox' provider...
==> node2: Clearing any previously set forwarded ports...
==> node2: Clearing any previously set network interfaces...
==> node2: Preparing network interfaces based on configuration...
    node2: Adapter 1: nat
    node2: Adapter 2: hostonly
    node2: Adapter 3: intnet
==> node2: Forwarding ports...
    node2: 22 (guest) => 2222 (host) (adapter 1)
==> node2: Running 'pre-boot' VM customizations...
==> node2: Booting VM...
==> node2: Waiting for machine to boot. This may take a few minutes...
    node2: SSH address: 127.0.0.1:2222
    node2: SSH username: vagrant
    node2: SSH auth method: private key
    node2: Warning: Connection reset. Retrying...
    node2: Warning: Connection aborted. Retrying...
    node2: Warning: Remote connection disconnect. Retrying...
==> node2: Machine booted and ready!
==> node2: Checking for guest additions in VM...
==> node2: Setting hostname...
==> node2: Configuring and enabling network interfaces...
==> node2: Configuring proxy environment variables...
==> node2: Configuring proxy for Yum...
==> node2: Mounting shared folders...
    node2: /vagrant => C:/Users/Francisco/Downloads/vagrant-projects/OracleRAC
==> node2: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> node2: flag to force provisioning. Provisioners marked to run always will still run.
==> node1: Clearing any previously set forwarded ports...
==> node1: Fixed port collision for 22 => 2222. Now on port 2200.
==> node1: Clearing any previously set network interfaces...
==> node1: Preparing network interfaces based on configuration...
    node1: Adapter 1: nat
    node1: Adapter 2: hostonly
    node1: Adapter 3: intnet
==> node1: Forwarding ports...
    node1: 22 (guest) => 2200 (host) (adapter 1)
==> node1: Running 'pre-boot' VM customizations...
==> node1: Booting VM...
==> node1: Waiting for machine to boot. This may take a few minutes...
    node1: SSH address: 127.0.0.1:2200
    node1: SSH username: vagrant
    node1: SSH auth method: private key
    node1: Warning: Connection reset. Retrying...
    node1: Warning: Connection aborted. Retrying...
    node1: Warning: Remote connection disconnect. Retrying...
==> node1: Machine booted and ready!
==> node1: Checking for guest additions in VM...
==> node1: Setting hostname...
==> node1: Configuring and enabling network interfaces...
==> node1: Configuring proxy environment variables...
==> node1: Configuring proxy for Yum...
==> node1: Mounting shared folders...
    node1: /vagrant => C:/Users/Francisco/Downloads/vagrant-projects/OracleRAC
==> node1: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> node1: flag to force provisioning. Provisioners marked to run always will still run.

C:\Users\Francisco\Downloads\vagrant-projects\OracleRAC>vagrant ssh node1

│▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│
 Oracle RAC (Real Application Cluster) Vagrant box for KVM/libVirt or VirtualBox
 Copyright (c) 1982-2020 Oracle and/or its affiliates
----------------------------------------------------------------------------------
 Author: Ruggero Citton <ruggero.citton@oracle.com>
         RAC Pack, Cloud Innovation and Solution Engineering Team
│▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│


--------------------
Detected virtualbox
--------------------
getting Proxy Configuration from Host...
Last login: Wed Aug 25 09:28:09 2021 from 10.0.2.2

Welcome to Oracle Linux Server release 7.9 (GNU/Linux 5.4.17-2036.100.6.1.el7uek.x86_64)

The Oracle Linux End-User License Agreement can be viewed here:

  * /usr/share/eula/eula.en_US

For additional packages, updates, documentation and community help, see:

  * https://yum.oracle.com/

[vagrant@node1 ~]$ sudo su -
Last login: Tue Aug 24 18:51:06 -05 2021 on pts/0
[root@node1 ~]# /tmp/vagrant-shell
-----------------------------------------------------------------
2021-08-25 09:35:51: Setup the environment variables
-----------------------------------------------------------------
-----------------------------------------------------------------
INFO: 2021-08-25 09:35:51: Checking parameters
-----------------------------------------------------------------
-----------------------------------------------------------------
INFO: 2021-08-25 09:35:51: Fix locale warnings
-----------------------------------------------------------------
-----------------------------------------------------------------
INFO: 2021-08-25 09:35:51: Set system time zone
-----------------------------------------------------------------
Invalid number of arguments.
-----------------------------------------------------------------
INFO: 2021-08-25 09:35:51: Setting-up /u01 disk
-----------------------------------------------------------------
Not supported provider:
-----------------------------------------------------------------
INFO: 2021-08-25 09:35:51: Install base packages
-----------------------------------------------------------------
ol7_UEKR6                                                                                                                                                                                   | 3.0 kB  00:00:00
ol7_addons                                                                                                                                                                                  | 3.0 kB  00:00:00
ol7_developer                                                                                                                                                                               | 3.0 kB  00:00:00
ol7_developer_EPEL                                                                                                                                                                          | 3.6 kB  00:00:00
ol7_latest                                                                                                                                                                                  | 3.6 kB  00:00:00
ol7_optional_latest                                                                                                                                                                         | 3.0 kB  00:00:00
ol7_software_collections                                                                                                                                                                    | 3.0 kB  00:00:00
(1/6): ol7_developer_EPEL/x86_64/updateinfo                                                                                                                                                 | 423 kB  00:00:06
(2/6): ol7_optional_latest/x86_64/updateinfo                                                                                                                                                | 1.3 MB  00:00:10
(3/6): ol7_latest/x86_64/updateinfo                                                                                                                                                         | 3.3 MB  00:00:12
(4/6): ol7_optional_latest/x86_64/primary_db                                                                                                                                                | 5.4 MB  00:00:20
(5/6): ol7_developer_EPEL/x86_64/primary_db                                                                                                                                                 |  14 MB  00:00:38
(6/6): ol7_latest/x86_64/primary_db                                                                                                                                                         |  34 MB  00:00:42
Package deltarpm-3.6-3.el7.x86_64 already installed and latest version
Package expect-5.45-14.el7_1.x86_64 already installed and latest version
Package tree-1.6.0-10.el7.x86_64 already installed and latest version
Package unzip-6.0-22.el7_9.x86_64 already installed and latest version
Package zip-3.0-11.el7.x86_64 already installed and latest version
Nothing to do
Package oracle-database-preinstall-18c-1.0-1.el7.x86_64 already installed and latest version
Nothing to do
Package oracleasm-support-2.1.11-2.el7.x86_64 already installed and latest version
Nothing to do
-----------------------------------------------------------------
INFO: 2021-08-25 09:37:05: Add extra OS packages
-----------------------------------------------------------------
Package bc-1.06.95-13.el7.x86_64 already installed and latest version
Nothing to do
Package binutils-2.27-44.base.0.3.el7.x86_64 already installed and latest version
Nothing to do
Package compat-libcap1-1.10-7.el7.x86_64 already installed and latest version
Nothing to do
Package compat-libstdc++-33-3.2.3-72.el7.x86_64 already installed and latest version
Nothing to do
Package compat-libstdc++-33-3.2.3-72.el7.i686 already installed and latest version
Nothing to do
Package fontconfig-devel-2.13.0-4.3.el7.x86_64 already installed and latest version
Nothing to do
Package glibc-2.17-324.0.1.el7_9.i686 already installed and latest version
Nothing to do
Package glibc-2.17-324.0.1.el7_9.x86_64 already installed and latest version
Nothing to do
Package glibc-devel-2.17-324.0.1.el7_9.i686 already installed and latest version
Nothing to do
Package glibc-devel-2.17-324.0.1.el7_9.x86_64 already installed and latest version
Nothing to do
Package ksh-20120801-142.0.1.el7.x86_64 already installed and latest version
Nothing to do
Package libaio-0.3.109-13.el7.i686 already installed and latest version
Nothing to do
Package libaio-0.3.109-13.el7.x86_64 already installed and latest version
Nothing to do
Package libaio-devel-0.3.109-13.el7.i686 already installed and latest version
Nothing to do
Package libaio-devel-0.3.109-13.el7.x86_64 already installed and latest version
Nothing to do
Package libX11-1.6.7-3.el7_9.i686 already installed and latest version
Nothing to do
Package libX11-1.6.7-3.el7_9.x86_64 already installed and latest version
Nothing to do
Package libXau-1.0.8-2.1.el7.i686 already installed and latest version
Nothing to do
Package libXau-1.0.8-2.1.el7.x86_64 already installed and latest version
Nothing to do
Package libXi-1.7.9-1.el7.i686 already installed and latest version
Nothing to do
Package libXi-1.7.9-1.el7.x86_64 already installed and latest version
Nothing to do
Package libXtst-1.2.3-1.el7.i686 already installed and latest version
Nothing to do
Package libXtst-1.2.3-1.el7.x86_64 already installed and latest version
Nothing to do
Package libgcc-4.8.5-44.0.3.el7.i686 already installed and latest version
Nothing to do
Package libgcc-4.8.5-44.0.3.el7.x86_64 already installed and latest version
Nothing to do
Package rdma-core-devel-22.4-6.el7_9.x86_64 already installed and latest version
Nothing to do
Package libstdc++-4.8.5-44.0.3.el7.i686 already installed and latest version
Nothing to do
Package libstdc++-4.8.5-44.0.3.el7.x86_64 already installed and latest version
Nothing to do
Package libstdc++-devel-4.8.5-44.0.3.el7.i686 already installed and latest version
Nothing to do
Package libstdc++-devel-4.8.5-44.0.3.el7.x86_64 already installed and latest version
Nothing to do
Package libxcb-1.13-1.el7.i686 already installed and latest version
Nothing to do
Package libxcb-1.13-1.el7.x86_64 already installed and latest version
Nothing to do
Package 1:make-3.82-24.el7.x86_64 already installed and latest version
Nothing to do
Package 1:nfs-utils-1.3.0-0.68.0.1.el7.1.x86_64 already installed and latest version
Nothing to do
Package net-tools-2.0-0.25.20131004git.el7.x86_64 already installed and latest version
Nothing to do
Package python-2.7.5-90.0.3.el7.x86_64 already installed and latest version
Nothing to do
Package 1:python-configshell-1.1.26-1.0.1.el7.noarch already installed and latest version
Nothing to do
Package python-rtslib-2.1.74-1.0.3.el7_9.noarch already installed and latest version
Nothing to do
Package python-six-1.9.0-2.el7.noarch already installed and latest version
Nothing to do
Package 1:smartmontools-7.0-2.el7.x86_64 already installed and latest version
Nothing to do
Package sysstat-10.1.5-19.el7.x86_64 already installed and latest version
Nothing to do
Package targetcli-2.1.53-1.0.1.el7_9.noarch already installed and latest version
Nothing to do
Package unixODBC-2.3.1-14.0.1.el7.x86_64 already installed and latest version
Nothing to do
Package chrony-3.4-1.0.1.el7.x86_64 already installed and latest version
Nothing to do
-----------------------------------------------------------------
INFO: 2021-08-25 09:39:44: Setup /etc/hosts
-----------------------------------------------------------------
-----------------------------------------------------------------
INFO: 2021-08-25 09:39:44: Setup SCAN on /etc/hosts
-----------------------------------------------------------------
-----------------------------------------------------------------
INFO: 2021-08-25 09:39:44: Setup /etc/resolv.conf
-----------------------------------------------------------------
-----------------------------------------------------------------
INFO: 2021-08-25 09:39:44: Setup chronyd service
-----------------------------------------------------------------
200 OK
-----------------------------------------------------------------
INFO: 2021-08-25 09:39:44: Setting-up shared disks partions
-----------------------------------------------------------------
Not supported provider:
-----------------------------------------------------------------
INFO: 2021-08-25 09:39:44: Setup oracle and grid user
-----------------------------------------------------------------
groupdel: cannot remove the primary group of user 'grid'
groupadd: group 'oinstall' already exists
groupadd: group 'dbaoper' already exists
groupadd: group 'asmadmin' already exists
groupadd: group 'asmoper' already exists
groupadd: group 'asmdba' already exists
useradd: user 'grid' already exists
-----------------------------------------------------------------
INFO: 2021-08-25 09:39:45: Set oracle and grid limits
-----------------------------------------------------------------
-----------------------------------------------------------------
INFO: 2021-08-25 09:39:45: Create GI_HOME and DB_HOME directories
-----------------------------------------------------------------
-----------------------------------------------------------------
INFO: 2021-08-25 09:39:46: Set user env
-----------------------------------------------------------------
-----------------------------------------------------------------
INFO: 2021-08-25 09:39:46: Set root, oracle and grid password
-----------------------------------------------------------------
Changing password for user root.
passwd: Authentication token manipulation error
Changing password for user grid.
passwd: Authentication token manipulation error
Changing password for user oracle.
passwd: Authentication token manipulation error
/tmp/vagrant-shell: line 659: [: node1: unary operator expected
-----------------------------------------------------------------
INFO: 2021-08-25 09:39:53: ASMLib disks label setup
-----------------------------------------------------------------
Not supported provider:
/tmp/vagrant-shell: line 717: [: node1: unary operator expected
-----------------------------------------------------------------
INFO: 2021-08-25 09:39:53: Running user-defined post-setup scripts
-----------------------------------------------------------------
[root@node1 ~]#

**Comment by faguirre154** [comment]
I installed OracleRAC vagrant project with warnings in my Lenovo Laptop with 16 Gb RAM Windows 10 Home Single Language Version 21H1, I am attaching installation log
I destroy my previous environment thru Windows command prompt CMD> vagrant destroy -f
I set "mem_size: 6144" instead of default 8192 in "[your path]\vagrant-projects\OracleRAC\config\vagrant.yml" (previously I saved a copy of original vagrant.yml) and then execute "vagrant up" again

Last question: To install ASMFD, Should I need to change ASM_LIB_TYPE=ASMLIB by ASM_LIB_TYPE=ASMFD in "[your path]\vagrant-projects\OracleRAC\config\setup.env file?
[success_orcl_rac_vagrant_projects.txt](https://github.com/oracle/vagrant-projects/files/7113928/success_orcl_rac_vagrant_projects.txt)

**Comment by rcitton** [comment]
8G for two RAC nodes means you have not memory for your OS... and windows needs at least 4G for "acceptable" performance.
So 6G each for the two nodes is really the starting point and on windows the env it may not perform so much..
Said that, ASMFD is supported with latest release only, then you should get the repository again (git clone ..) and start again from scratch   vagrant destroy -f, vagrant up ...

**Comment by faguirre154** [comment]
node1: SUCCESS: 2021-09-08 02:16:32: Oracle RAC on Vagrant has been created successfully!
following your previus recomendations but still using ASMlib instead of ASMFD:
node2: INFO: 2021-09-08 00:36:20: ASMLib disks label setup
so I must change ASM_LIB_TYPE=ASMFD in [your path]\vagrant-projects\OracleRAC\config\setup.env file in order that happen?
[oracle-vagrant-rac-output.txt](https://github.com/oracle/vagrant-projects/files/7128841/oracle-vagrant-rac-output.txt)

**Comment by rcitton** [comment]
latest OracleRAC vagrant-project (of ~12 days ago) is introducing support for ASMFD. you need to get it and on vagrant.yml, a new parameter is present: asm_lib_type: 'ASMFD'  or asm_lib_type: 'ASMLIB'
