### ISSUE TITLE
Oracle Database 21c Express Edition

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-projects#380]
Congratulations on the Oracle Database 21c XE release!

I've created a 21c XE Vagrant build, based on the 18c XE project in this repository. You can see it [here](https://github.com/PaulNeumann/vagrant-test/tree/main/OracleDatabase/21.3.0-XE). If it would be helpful, I'd be happy to submit a PR for your consideration.

Again, congratulations on the release.

**Comment by gvenzl** [comment]
Hi @PaulNeumann, a PR would be helpful and very much appreciated :)
