### ISSUE TITLE
DATA Diskgroup compatibility option

### ISSUE THREAD

**Issue by Project-42** [oracle/vagrant-projects#404]
EDIT: This is referring to "OracleRAC" project 

I was wondering if there is any option change the Compatible parameters during the creation of the cluster?

tried adding the following to the setup.sh script, but can't not find the actual parameter name anywhere:

```
    oracle.install.asm.SYSASMPassword=${SYS_PASSWORD} \\
    oracle.install.asm.diskGroup.name=DATA \\
    oracle.install.asm.diskGroup.redundancy=EXTERNAL \\
    oracle.install.asm.diskGroup.AUSize=4 \\
    oracle.install.asm.diskGroup.compatible.asm='11.2.0.2.0' \\
    oracle.install.asm.diskGroup.compatible.rdbms='11.2.0.2.0' \\
    oracle.install.asm.diskGroup.compatible.advm='11.2.0.2.0' \\
EOF
```
Not an actual issue, but maybe  someone around here that can know the answer :)

**Comment by rcitton** [comment]
the response file is not providing "compatible" options. The only way I see is to have a dummy DG created by gridsetup and the additional DG for database usage created manually specifying the compatible as you need.
