### ISSUE TITLE
Different Memory and CPU for Worker and Master Node

### ISSUE THREAD

**Issue by rikumabokss** [oracle/vagrant-projects#409]
Hi,

For OCNE, how one can have different memory and cpu for worker and master nodes.

Thanks

**Comment by hussam-qasem** [comment]
Dear @AmedeeBulle,

In `.env`, I created new variables, e.g.:
```Shell
OPERATOR_CPUS=1
OPERATOR_MEMORY=1024
MASTER_CPUS=2
MASTER_MEMORY=2048
WORKER_CPUS=1
WORKER_MEMORY=1024
```
and I modified the `Vagrantfile` accordingly. If you're happy with that approach, I can submit a PR. (Also to bump OLCNE to v1.4).

**Comment by AmedeeBulle** [comment]
That would work for me -- contributions are always welcome!

Please review the [CONTRIBUTING.md](https://github.com/oracle/vagrant-projects/blob/main/CONTRIBUTING.md) document before submitting a PR

**Comment by hussam-qasem** [comment]
Dear @rafabene. Would you be so kind to review my [PR](https://github.com/oracle/vagrant-projects/pull/420) please?

I would like to make further contributions to fix annoying errors/warnings in `/var/log/messages` as well.

Thank you!

**Comment by rafabene** [comment]
Hi @hussam-qasem .

Thanks for the PR. 

It has been approved, but I don't have permission to merge it.

Thank you.
