### ISSUE TITLE
"Login incorrect" after attempting to login

### ISSUE THREAD

**Issue by samperrow** [oracle/vagrant-projects#411]
**Describe the issue**
After installing and running everything, the shell window opens asking me to enter my "localhost login". I enter "admin", and then enter the password that was supplied during the installation process. After many attempts, I always receive the "Login incorrect" message, and I cannot login to the VM.

A clear and concise description of what the issue is.  
Explain what commands you ran, what you expected to happen and what actually happened.

**Environment (please complete the following information):**

- Host OS: Windows 11
- Kernel version (for Linux host): n/a
- Vagrant version: 2.2.19
- Vagrant provider:
  - For VirtualBox:
    - VirtualBox version: 6.1.30
 - For libvirt:    - Vagrant-libvirt plugin version: no vagrant plugins
    - QEMU and libvirt version:  virsh not installed.

- Vagrant project:  Oracle Linux 7

**Additional information**

**Comment by totalamateurhour** [comment]
What commands did you run, starting with `git clone` before you are asked for localhost login?

**Comment by samperrow** [comment]
I did steps #1-6 exactly from the readme, copied the password onto a separate file, ran the vm, and then it asked for my localhost login followed by the password. I enter the password, and it has been failing every time.

**Comment by totalamateurhour** [comment]
which README?

**Comment by samperrow** [comment]
this one: [https://github.com/oracle/vagrant-projects/tree/main/OracleAPEX#readme](https://github.com/oracle/vagrant-projects/tree/main/OracleAPEX#readme)

**Comment by totalamateurhour** [comment]
Are you otherwise able to use VirtualBox on this Windows 11 system?

**Comment by samperrow** [comment]
yes, I have ran other VM's on it without any problems.

**Comment by totalamateurhour** [comment]
can you confirm that the prompt for "localhost login:" is generated by a VM, not Windows itself? There shouldn't be any login required at this point and the credentials would certainly not be the database admin credentials you provided.

**Comment by samperrow** [comment]
yes- I start up the VM in Virtualbox, another windows opens up and the VM boots up, then this is a screenshot of what I get:
[https://imgur.com/a/37GU1Sz](https://imgur.com/a/37GU1Sz)

**Comment by totalamateurhour** [comment]
@PaulNeumann - have you ever seen this?

**Comment by PaulNeumann** [comment]
@samperrow @totalamateurhour Starting the APEX VM through VirtualBox GUI isn't the usual way to use it. Typically, the VM is started from the command line using `vagrant up`, rather than starting it from the GUI. When the VM is started from the VirtualBox GUI, using either `root` or `vagrant` for the login user and `vagrant` as the password should allow one to log in.

That said, it's easier to start the VM using `vagrant up`, then log in using `vagrant ssh`. The SSH connection shouldn't require a password. In a lot of cases, it's not necessary to SSH to the VM, though:

- To log into APEX, just use a browser and open [http://localhost:8080/ords/](http://localhost:8080/ords/). The workspace should be `internal`, the user should be `admin`, and the password should be the password that was displayed at the end of VM provisioning.
- To log into Oracle Database, one can use SQL Developer or SQL*Plus, if these tools are installed on the host. The server will be `localhost`, and the database will be `XE` for the container database or `XEPDB1` for the pluggable database. One can use the `SYS`, `SYSTEM` or `PDBADMIN` database account to log in. (The `PDBADMIN` account applies to the pluggable database only.) The passwords for these database accounts is also the one that was displayed at the end of VM provisioning.

I hope this helps.

**Comment by totalamateurhour** [comment]
@samperrow - did start the VM using the vagrant commands, right?

**Comment by samperrow** [comment]
@PaulNeumann I was able to login via ssh after doing `vagrant up`. However the `vagrant`/`vagrant`, or `root`/`vagrant` user/pw combo have not worked.
After I ssh'd in, I try to reach http://localhost:8080/ords in my browser, but I cannot connect to that URL locally. Probably something is wrong with my network settings.

**Comment by AmedeeBulle** [comment]
> However the `vagrant`/`vagrant`, or `root`/`vagrant` user/pw combo have not worked.

Both accounts are locked, you can only login as `vagrant` through `ssh` and become `root` with `sudo`.

If you absolutely want to login with a password, you have to set it yourself (but that should not be necessary).

**Comment by PaulNeumann** [comment]
@AmedeeBulle Thank you, sir. I appreciate the correction.

@samperrow Here are a couple of things to try:

- When you connect to APEX, make sure to include the trailing slash in the APEX URL ([http://localhost:8080/ords/](http://localhost:8080/ords/))
- If that doesn't help, try rebooting the VM (`vagrant reload` from the command line).
- If you still can't connect to APEX after rebooting the VM, something may have gone wrong during provisioning. Do you remember seeing any error messages when you ran `vagrant up` the first time?

**Comment by PaulNeumann** [comment]
@samperrow I thought of something else to check. When you downloaded the APEX and ORDS installers, were the filenames `apex-latest.zip` and `ords-latest.zip`? If so, APEX and ORDS didn't actually get installed when you provisioned the VM. The installation scripts were created before Oracle started using the `-latest` file naming convention, and they don't recognize the `-latest` filenames.

If you downloaded the `-latest` files, please try the following:

- Rename `apex-latest.zip` to `apex_21.2_en.zip`
- Rename `ords-latest.zip` to `ords-21.3.1.301.2050.zip`
- Rebuild the VM (`vagrant destroy`, then `vagrant up`)

This should allow the APEX and ORDS installations to work. I'll submit a PR to update the installation scripts as soon as I can.

I hope this helps.

**Comment by samperrow** [comment]
I did have something wrong with my initial installation. I ran into a couple of other issues during the install:
1) I downloaded the default oracle db from the link provided in the readme, which is version 21c. Since the installer is looking for version 18c, it will run into an error:

`oracle-18c-apex: Cannot open: /vagrant/oracle-database-xe-18c-*.x86_64.rpm. Skipping.`
`oracle-18c-apex: Nothing to do`
`oracle-18c-apex: INSTALLER: Oracle software installed`
`oracle-18c-apex: mv: cannot stat ‘/etc/sysconfig/oracle-xe-18c.conf’: No such file or directory`
`oracle-18c-apex: mkdir: cannot create directory ‘/opt/oracle’: Permission denied`
`oracle-18c-apex: /tmp/vagrant-shell: line 57: /etc/init.d/oracle-xe-18c: No such file or directory`

I suggest replacing the link to the db with this one below to eliminate that confusion: 
[https://download.oracle.com/otn-pub/otn_software/db-express/oracle-database-xe-18c-1.0-1.x8c6_64.rpm](https://download.oracle.com/otn-pub/otn_software/db-express/oracle-database-xe-18c-1.0-1.x8c6_64.rpm)

2. I believe the `$ORDS_HOME` variable in OracleApex/scripts/ords.sh points to an incorrect file path. (Maybe after the unzip on line 41 the file path changes?). This causes the error below for me: 

`oracle-18c-apex:   inflating: ords-21.3.1.301.2050/params/ords_params.properties`
`oracle-18c-apex: INSTALLER: Oracle Rest Data Services extracted to ORACLE_BASE`
`oracle-18c-apex: Error: Unable to access jarfile /opt/oracle/ords/ords.war`
`oracle-18c-apex: /tmp/vagrant-shell: line 52: /opt/oracle/ords/params/ords_params.properties: No such file or directory`
`oracle-18c-apex: -bash: line 0: cd: /opt/oracle/product/18c/dbhomeXE/apex: No such file or directory`

**Comment by PaulNeumann** [comment]
@samperrow Yes, it'd be helpful to update the download link. I think the `ORDS_HOME` variable is probably OK, and that the error you saw is due to not having Oracle Database 18c XE installed, but I'll  take a look.

**Comment by samperrow** [comment]
@PaulNeumann I had resolved the correct database version, then when I tried to reinstall i ran into issue #2

**Comment by PaulNeumann** [comment]
@samperrow I'm not able to reproduce this issue. The VM builds and works correctly for me. My environment is very similar to yours--Windows 11 Pro Version 21H2 (OS Build 22000.348), VirtualBox 6.1.30, Vagrant 2.2.19.

Please try the following:

- Double-check to make sure that all Hyper-V features are disabled on your computer. See [Hyper-V on Windows hosts](https://github.com/oracle/vagrant-projects#hyper-v-on-windows-hosts) in the top-level [README.md](https://github.com/oracle/vagrant-projects/blob/main/README.md) file in this repository.
- Completely remove the VM by changing to the `vagrant-projects\OracleAPEX` directory and running `vagrant destroy`. Running `vagrant provision` isn't sufficient to clean up after a failed installation.
- While still in the `vagrant-projects\OracleAPEX` directory, verify that you're using the latest version of the Oracle Linux 7 Vagrant box by running the command `vagrant box update`.
- Undo any changes you've made to any of the files in the `vagrant-projects\OracleAPEX` directory or its subdirectories (if applicable).
- Make sure that the only files you've added to the `vagrant-projects\OracleAPEX` directory are the database, APEX and ORDS installers (`oracle-database-xe-18c-1.0-1.x86_64.rpm`, `apex_21.2_en.zip` and `ords-21.3.1.301.2050.zip`).
- Open a PowerShell window, change to the `vagrant-projects\OracleAPEX` directory, and run `vagrant up | Tee-Object provision.log`. This will build the VM and save the output from `vagrant up` in a file called `provision.log`.
- If there are any errors, or the VM doesn't work properly after provisioning, please copy the `provision.log` file to a gist and post a link to the gist here. That will help us figure out what's going on.

**Comment by AmedeeBulle** [comment]
I assume this is solved in the meantime -- @PaulNeumann thank you for the help on this issue.
