### ISSUE TITLE
Missing information of the PDF version of the user manual

### ISSUE THREAD

**Issue by pguerin3** [oracle/vagrant-projects#415]
**HTML version of the user manual**
The link to the chapter 6.7 Host-Only Networking of the HTML user manual is here:
https://www.virtualbox.org/manual/UserManual.html#network_hostonly

And at the tail of chapter 6.7 Host-Only Networking there is the following information:
```
On Linux, Mac OS X and Solaris Oracle VM VirtualBox will only allow IP addresses in 192.168.56.0/21 range to be assigned to host-only adapters. For IPv6 only link-local addresses are allowed. If other ranges are desired, they can be enabled by creating /etc/vbox/networks.conf and specifying allowed ranges there. For example, to allow 10.0.0.0/8 and 192.168.0.0/16 IPv4 ranges as well as 2001::/64 range put the following lines into /etc/vbox/networks.conf:

      * 10.0.0.0/8 192.168.0.0/16
      * 2001::/64
      
Lines starting with the hash # are ignored. Next example allows any addresses, effectively disabling range control:

      * 0.0.0.0/0 ::/0
      
If the file exists, but no ranges are specified in it, no addresses will be assigned to host-only adapters. The following example effectively disables all ranges:

      # No addresses are allowed for host-only adapters
```
This looks like valid information that all Virtualbox users on Linux, Mac OS X and Solaris need to know about.

**PDF version of the user manual**
The link to the PDF is here:
https://download.virtualbox.org/virtualbox/UserManual.pdf
Go to the chapter 6.7 Host-Only Networking, and you can see that the information in the HTML version of the manual is absent from the PDF version of the manual.

This a source of confusion for Virtualbox users that are reading the PDF version of the manual, and don't know about the information in the HTML version of the manual.

**Comment by AmedeeBulle** [comment]
The PDF version is still for version 6.1.16, which predates these changes (introduced in 6.1.18).

Closing this issue as this a really a VirtualBox matter.

@scoter-oracle FYI

**Comment by pguerin3** [comment]
Sorry - I posted in the wrong forum.

But perhaps a note can be placed in the vagrant-projects markdown, that the Linux, Mac OS X and Solaris users need to create a /etc/vbox/networks.conf file with the correct information.

**Comment by AmedeeBulle** [comment]
Yes, as I mentioned in #414, we need to either document the requirement or update the projects to be compliant to the new VirtualBox restrictions.
(I would be in favour of the latter)
