### ISSUE TITLE
OLCNE needs to be renamed to OCNE

### ISSUE THREAD

**Issue by mitchds** [oracle/vagrant-projects#426]
**Describe the issue**

OLCNE project name is deprecated. Please rename project to OCNE

**Comment by hussam-qasem** [comment]
Though the CLI is still called [`olcnectl`](https://docs.oracle.com/en/operating-systems/olcne/1.4/olcnectl/intro.html#help) and not `ocnectl`.

**Comment by mitchds** [comment]
Sadly true, what a conundrum. Rename the repo, or rename the command. I doubt the latter is easily doable.

**Comment by scoter-oracle** [comment]
code fixed, we just need to also rename the main folder.

**Comment by hussam-qasem** [comment]
Dear @scoter-oracle . I submitted a new PR for the folder name change.

**Comment by scoter-oracle** [comment]
Thanks for that @hussam-qasem
