### ISSUE TITLE
OCNE: kubernetes dashboard link in README is incorrect

### ISSUE THREAD

**Issue by mitchds** [oracle/vagrant-projects#427]
**Describe the issue**

1. The k8s dashboard link in the README is incorrect.
``
 http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
``
should be
``
 http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy
``
as the dashboard is now installed in its own namespace. 

2. Also for convenience getting the k8s-dashboard token should be added to the README 
``
 $ kubectl -n kube-system describe $(kubectl -n kube-system get secret -n kube-system -o name | grep namespace) | grep token:
 ``

**Comment by hussam-qasem** [comment]
Hello @mitchds. I was just about to send a PR for the exact thing! I noticed the name space was incorrect. For the token, I prefer to use `jsonpath` over grep:
```
kubectl -n kubernetes-dashboard get secret -o=jsonpath='{.items[?(@.metadata.annotations.kubernetes\.io/service-account\.name=="kubernetes-dashboard")].data.token}' | base64 --decode
```
I'll also mention that in the documentation.

**Comment by mitchds** [comment]
Yes, either is fine, just that the one i mentioned is what's in the doc section 5.2
 ```
https://docs.oracle.com/en/operating-systems/olcne/orchestration/dashboard.html#dashboard-local
```
