### ISSUE TITLE
Could not install module error

### ISSUE THREAD

**Issue by pguerin3** [oracle/vagrant-projects#454]
**Error installing with high availability enabled**
No problem, if I don't enable the high-availability feature:
![image](https://user-images.githubusercontent.com/47326729/193794251-313fd032-e91c-49a2-a974-bcbb56d161c9.png)

But if I enable the feature (ie 3 master nodes), then the last master node will fail with:
![image](https://user-images.githubusercontent.com/47326729/193794941-247cdc67-1829-4fa4-aee6-33fabb2a82a0.png)

**Environment:**

- Host OS: Fedora 36 with 32GB of physical memory
- Kernel version (for Linux host): fedora 5.19.12-200
- Vagrant version: 2.2.19
- Vagrant provider:
  - For VirtualBox:
    - VirtualBox version: 6.1.38r153438
- Vagrant project:  OLCNE

**Additional information**

Add any other information about the issue here (console log, ...).

**Comment by pguerin3** [comment]
Correction - the last master node does install, so 3 masters in total are installed.
But something is attempting to be installed after the 3rd master node.

**Comment by hussam-qasem** [comment]
Installing the Kubernetes module is failing. The likely cause is too little memory on your worker node.

If you’re using the [`vagrant-env`](https://github.com/oracle/vagrant-projects/tree/main/OCNE#how-to-configure) plug-in, copy your `.env` file to `.local.env` and increase the memory allocated for your `WORKER_MEMORY`. If you don’t use the plug-in edit the `Vagrantfile` directly (not recommended).

**Comment by hussam-qasem** [comment]
I suggest closing this issue. I can replicate by setting `WORKER_MEMORY` in `.env.local` to low amount.

**Comment by pguerin3** [comment]
What value did you use for the WORKER_MEMORY?

**Comment by hussam-qasem** [comment]
> What value did you use for the WORKER_MEMORY?

To fail, usually less than `680`.

To work, at least `1024`. Though `2048` or higher would make more sense to run useful workload on your cluster and/or to test.

**Comment by hussam-qasem** [comment]
@pguerin3 - I just took a closer look at your screenshot. How exactly did you enable HA? In your screenshot, deploying the K8s modules is happening on `master1`, which shouldn't be the case in HA setup. 

To enable HA, simply set `MULTI_MASTER=true` in `.env.local` (assuming you have the `vagrant-env` plugin). This will:
* auto-set `STANDALONE_OPERATOR=true`;
* provision a new VM named `operator`

K8s modules will then be installed once the `operator` VM is up and running.

**Comment by pguerin3** [comment]
I have now installed the plugin and created the following .env.local file:
```
MULTI_MASTER=true
WORKER_MEMORY=2048
SUBNET=192.168.56
```
Plus the new files mentioned in this issue: [468](https://github.com/oracle/vagrant-projects/issues/468)
I'll report back on the result soon.

**Comment by hussam-qasem** [comment]
Hi @pguerin3 
Code is already merged. You can do a `git clone` to get the latest. 
I also sugguest you copy the full [.env](https://github.com/oracle/vagrant-projects/blob/main/OCNE/.env) onto `.env.local` so you can play around.

**Comment by pguerin3** [comment]
The error I get is:
![image](https://user-images.githubusercontent.com/47326729/218696171-1f9a9489-1420-44ef-9341-c3b0c64bbfb2.png)

**Environment**
Host OS: Oracle Linux 9 with 24GB memory
Kernel version (for Linux host): 5.14.0-162.6.1.el9_1.x86_64
Vagrant version: 2.3.4
Vagrant provider: Virtualbox 7.0.6r155176
Vagrant project: OLCNE

**Comment by hussam-qasem** [comment]
I would need more information to help. Would you:
1) Login to your operator node, and share the log file in question:
```
vagrant ssh operator
cat /var/tmp/cmd_OXQEP.log
```

2) Login to your `master1` node and check with repo provides `conmon`
```
vagrant ssh master1
dnf list installed conmon
```

Also, I would recommend you set `VERBOSE=true` in your `.env.local` and try again:
```
vagrant destroy -f
vagrant up
```

(again, I'm assuming you have a current clone of this Git repo)

**Comment by pguerin3** [comment]
Finally I got the cluster up.
![image](https://user-images.githubusercontent.com/47326729/219821900-4a5606b4-c3c9-4e10-b3e7-074ec723bbb8.png)

My issue is that a host with 24GB of memory is barely enough, so I had to find the right balance via trial and error for the VMs.
My .env.local looks like this:
```
MULTI_MASTER=true
WORKER_MEMORY=1048
OPERATOR_MEMORY=3128
MASTER_MEMORY=5128
SUBNET=192.168.56
```
To do anything useful with the cluster, I would say that you need a host with at least 32GB.

**Comment by hussam-qasem** [comment]
I'm glad your issue is resolved. I run all my tests on my old Intel MacBook with 16GB of RAM, and you're right, more RAM would be nice.
