### ISSUE TITLE
vagrant up stops with an error

### ISSUE THREAD

**Issue by witchi** [oracle/vagrant-projects#456]
I try to start the OracleDatabase 19.3.0 with `vagrant up` but it results always in an error and the gust instance doesn't run:

```
Mounting NFS shared folders... (stops here for long time)

The following ssh command responded with a non-zero exit status.
Vagrant assumes that this means the command failed.

mount -o vers=3 192.168.121.1:/opt/install/vagrant-projects/OracleDatabase/19.3.0 /vagrant
mount.nfs: Connection refused
```

I have set some firewall rules to open ports for NFS, but there are no differences:

```
firewall-cmd --list-all
service: mountd nfs rpc-bind ssh ldap ldaps http https dhcpv6-client
```

Environment
- OpenSuse Leap 15.4
- Kernel version (for Linux host): 5.14.21-150400.24.28-default SMP PREEMPT_DYNAMIC
- Vagrant version: 2.2.18
- Vagrant provider:
  - For libvirt:
    - Vagrant-libvirt plugin version: 0.7.0
    - Vagrant-env: 0.0.3
    - QEMU version:  qemu-kvm-6.2.0-150400.37.8.2.x86_64
    - libvirt version: libvirt-8.0.0-140400.5.8.x86_64
- Vagrant project:  OracleDatabase/19.3.0

**Comment by witchi** [comment]
Seems to work with

```
$ sudo firewall-cmd --permanent --zone=libvirt --add-service=nfs3 \
    && sudo firewall-cmd --permanent --zone=libvirt --add-service=nfs \
    && sudo firewall-cmd --permanent --zone=libvirt --add-service=rpc-bind \
    && sudo firewall-cmd --permanent --zone=libvirt --add-service=mountd \
    && sudo firewall-cmd --reload
```
(found on https://developer.fedoraproject.org/tools/vagrant/vagrant-nfs.html)

I have to allow the NFS ports on the firewall zone, which is used by the interface virbr1 (created by libvirt). On OpenSuse Leap 15.4 the zone is called libvirt.

**Comment by AmedeeBulle** [comment]
Indeed, it is the same for OL8, the libvirt bridge has its own zone - see https://blogs.oracle.com/linux/post/getting-started-with-the-vagrant-libvirt-provider-for-oracle-linux
