### ISSUE TITLE
OCNE: Fixes for OL8U7

### ISSUE THREAD

**Issue by hussam-qasem** [oracle/vagrant-projects#461]
I would like to submit a OCNE PR to enhance the following:
- Upgrade to OL8 [UEKR7](https://docs.oracle.com/en/operating-systems/olcne/1.5/relnotes/new.html#ocne-157)
- Change `Virtualbox` `nic_type` to `virtio` drivers.
- Install `openssl` toolkit package.
- Change `conmon` from `/usr/libexec/crio/conmon` to `/usr/bin/conmon` in `/etc/crio/crio.conf` - as `conmon` in `@ol8_x86_64_appstream` now overrides `@ol8_x86_64_olcne15`
- Remove `firewall-cmd --add-masquerade` from provisioning script issue #460 .

**Comment by scoter-oracle** [comment]
Code merged. Thanks for your contribution!
