### ISSUE TITLE
Send failure: Connection was reset

### ISSUE THREAD

**Issue by 13899665490** [oracle/vagrant-projects#467]
**Describe the issue**

A clear and concise description of what the issue is.  
Explain what commands you ran, what you expected to happen and what actually happened.

**Environment (please complete the following information):**

- Host OS: [e.g. Oracle Linux 8, macOS 10.14.6, Windows 10 Pro, ...]
- Kernel version (for Linux host): [run `uname -a`]
- Vagrant version: [e.g. 2.2.9]
- Vagrant provider:
  - For VirtualBox:
    - VirtualBox version: [e.g. 6.1.8r137981 -- run `vboxmanage -v`]
  - For libvirt:
    - Vagrant-libvirt plugin version: [e.g. 0.1.2 -- run `vagrant plugin list`]
    - QEMU and libvirt version:  
      If you have `virsh` installed run `virsh -c qemu:///system version --daemon`  
      Alternatively query your package manager with e.g.  
        `rpm -q qemu-kvm libvirt`,  
        `dpkg -l qemu-kvm libvirt\* | grep ^ii`, ...
- Vagrant project:  [e.g. OLCNE, OracleDatabase/19.3.0, ...]

**Additional information**

Add any other information about the issue here (console log, ...).

vagrant up send an error:
--------------------
Detected virtualbox
--------------------
getting Proxy Configuration from Host...
Bringing machine 'node2' up with 'virtualbox' provider...
Bringing machine 'node1' up with 'virtualbox' provider...
==> node2: Box 'oraclelinux/7' could not be found. Attempting to find and install...
    node2: Box Provider: virtualbox
    node2: Box Version: >= 0
There was an error while downloading the metadata for this box.
The error message is shown below:

Send failure: Connection was reset

but i can open https://oracle.github.io/vagrant-projects/boxes/oraclelinux/7.json

can i download the metadata other way ,then  put it into directory?

**Comment by 13899665490** [comment]
oh  i  download the metadata using the url in https://oracle.github.io/vagrant-projects/boxes/oraclelinux/7.json,which directory  should i put  the box in?

**Comment by 13899665490** [comment]
schannel: failed to receive handshake, SSL/TLS connection failed

new error ....

**Comment by AmedeeBulle** [comment]
You haven't specified which host you are using...

If it is Windows, ensure HyperV is not enabled (seel [Hyper-V on Windows hosts](https://github.com/oracle/vagrant-projects#hyper-v-on-windows-hosts))

You could download the box directly with `vagrant box add --name oraclelinux/7 https://yum.oracle.com/boxes/oraclelinux/ol7/OL7U9_x86_64-vagrant-virtualbox-b335.box`, but I'm afraid you might have networking issues not directly related to these boxes...

**Comment by 13899665490** [comment]
thanks very much, let me have a try

**Comment by 13899665490** [comment]
thx very much， it works

**Comment by AmedeeBulle** [comment]
Glad it helped
