### ISSUE TITLE
Could not process rule

### ISSUE THREAD

**Issue by pguerin3** [oracle/vagrant-projects#468]
Was executing a 'vagrant up' and during the creation of worker1, I get the 'Could not process rule'.

**Environment**

- Host OS:  Oracle Linux 9
- Kernel version (for Linux host):  5.14.0-162.6.1.el9_1.x86_64
- Vagrant version:  2.3.4
- Vagrant provider: Virtualbox 7.0.6r155176
- Vagrant project:  OLCNE

**Additional information**

![image](https://user-images.githubusercontent.com/47326729/213847145-8aa11ef9-a4c5-4dd9-8052-85599c2eb0ef.png)

**Comment by pguerin3** [comment]
Tried the following :
```
dnf install kernel-uek-modules kernel-uek-devel
rcvboxdrv setup
systemctl reboot
```
Still get the same error on 'vagrant up'.

**Comment by hussam-qasem** [comment]
Try:

```shell
sudo dnf install -y kernel-uek-modules-$(uname -r)
```

As described in this [response](https://github.com/oracle/vagrant-projects/issues/460#issuecomment-1352953348) issue #460 .

**Comment by pguerin3** [comment]
Already installed previously.

![image](https://user-images.githubusercontent.com/47326729/213902374-0ed1222c-0aff-4eb6-b6ef-f88712dcf943.png)

**Comment by hussam-qasem** [comment]
As of now, [OCNE does not support Oracle Linux 9](https://docs.oracle.com/en/operating-systems/olcne/1.5/quickinstall/hosts.html#os).

**Comment by pguerin3** [comment]
There is no dockerfile in here:
https://github.com/oracle/vagrant-projects/tree/main/OCNE

**Comment by hussam-qasem** [comment]
> There is no dockerfile in here:
> https://github.com/oracle/vagrant-projects/tree/main/OCNE

Sorry. I meant `Vagrantfile` - it was pointing to the correct file.

**Comment by pguerin3** [comment]
Inside the provision.sh, and inside the setup_repos() function, I added:
```
echo_do sudo dnf install -y kernel-uek-modules kernel-uek-devel
echo_do sudo dnf install -y kernel-uek-modules-"$(name -r)"
```
This change is successful as both worker nodes are created now.

**Comment by pguerin3** [comment]
The next problem is the master node, which fails with:
![image](https://user-images.githubusercontent.com/47326729/215297831-2018404d-bd67-4c7c-ab30-6fac7a698312.png)

**Comment by hussam-qasem** [comment]
> The next problem is the master node, which fails with a certificate error:
> 
> ![image](https://user-images.githubusercontent.com/47326729/215297831-2018404d-bd67-4c7c-ab30-6fac7a698312.png)

You also need to install `OpenSSL`, it’s there in the provision script I shared.

**Comment by pguerin3** [comment]
ok - I didn't realise that I had to copy the full scripts over to my local directory.
I have done that now, and the Vagrant Up works, and I have access to the 3 default VMs.
Thankyou.
