### ISSUE TITLE
OracleDatabase Getting Started instructions contain an unnecessary download step

### ISSUE THREAD

**Issue by guy-rouillier** [oracle/vagrant-projects#476]
**Describe the issue**
The Getting Started instructions for OracleDatabase include this statement:
"Download the installation zip file(s) from OTN into this directory - first time only: http://www.oracle.com/technetwork/database/enterprise-edition/downloads/index.html"  This is not necessary, at least not in all cases.  I set up OracleDatabase/21.3.0-XE, and the machine configuration process downloaded 21.3.0-XE automatically.

A clear and concise description of what the issue is.  
See above. The Getting Started instructions state to download a database zip file from OTN.  I did not have to do this; the normal installation process automatically downloaded all necessary software.

Explain what commands you ran, what you expected to happen and what actually happened.
I simply ran "vagrant up" in the D:\Oracle\vagrant-projects\OracleDatabase\21.3.0-XE> directory.  Vagrant created the machine, and automatically downloaded the database software.

**Environment (please complete the following information):**

- Host OS: [e.g. Oracle Linux 8, macOS 10.14.6, Windows 10 Pro, ...] Windows 7 Pro 64-bit
- Kernel version (for Linux host): [run `uname -a`] Version 6.1 Build 7601 Service Pack 1
- Vagrant version: [e.g. 2.2.9] 2.3.2
- Vagrant provider:
  - For VirtualBox:
    - VirtualBox version: [e.g. 6.1.8r137981 -- run `vboxmanage -v`] 7.0.6r155176
  Vagrant project:  OracleDatabase/21.3.0-XE

**Additional information**

Add any other information about the issue here (console log, ...).

**Comment by PaulNeumann** [comment]
The instructions in the `OracleDatabase/README.md` file contain an overview of the process, which may vary slightly for each project. This is why the "For more information please check the individual README within each directory!" statement appears at the end of the "Getting started" section.

Thanks for pointing out that this might be unclear. I'll submit a clarification for the code owner's consideration.

**Comment by guy-rouillier** [comment]
Thanks for clarifying.  The OracleDatabase/21.3.0-XE/README.md file states:

`This Vagrant project provisions Oracle Database automatically, using Vagrant, an Oracle Linux 8 box and a shell script.
`

So, it does indeed clarify that the database (and database software) will be automatically provisioned.
