### ISSUE TITLE
Oracle Database 23c Free

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-projects#478]
Congratulations on the Oracle Database 23c Free release!

I've created a 23c Free Vagrant build, based on the 21c XE project in this repository. If it would be helpful, I'd be happy to submit a PR for your consideration.

Again, congratulations on the release.

**Comment by totalamateurhour** [comment]
A PR is more than welcome!

**Comment by gvenzl** [comment]
Oh yeah, PRs from you, @PaulNeumann are always welcome! :) Please go ahead!
