### ISSUE TITLE
Previewing Ceph

### ISSUE THREAD

**Issue by hussam-qasem** [oracle/vagrant-projects#489]
The [OCNE 1.6 announcement](https://blogs.oracle.com/linux/post/oracle-cloud-native-environment-16-is-available) by @scoter-oracle, mentions that we can preview Ceph.

Would you kindly point me to the right [documentation](https://docs.oracle.com/en/operating-systems/olcne/) to get me started?

<img width="1095" alt="Screen Shot 2023-06-18 at 10 00 29 AM" src="https://github.com/oracle/vagrant-projects/assets/68053227/9ac07b74-aaac-4413-8f74-d4e4898a3f1e">

**Comment by scoter-oracle** [comment]
Hi, when something is announced as a tech-preview we are used to share the code (as we've done) without sharing documentation on how-to get the same installed and/or configured (we do not want to see anyone getting it deployed in production without knowing that it's not officially supported).
That said, I see two options for you: one (immediate) is to leverage the community documentation for those components while the second one is to wait for a bit to see OCNE 1.7 announced (release where documentation for Rook/Ceph/Kubevirt will be available). Hope this helps.

**Comment by scoter-oracle** [comment]
Rook/Ceph are now part of OCNE 1.7 release. Please follow our documentation on the same at https://docs.oracle.com/en/operating-systems/olcne/1.7/rook/#Oracle-Cloud-Native-Environment
