### ISSUE TITLE
Oracle Database 23ai Free

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-projects#505]
Congratulations on the Oracle Database 23ai Free release!

I've created a 23ai Free Vagrant build, based on the 23c Free project in this repository. If it would be helpful, I'd be happy to submit a PR for your consideration.

**Comment by gvenzl** [comment]
Hey @PaulNeumann,

Thanks a lot!

Yes, we would gladly have you submit a pull request :)
