### ISSUE TITLE
: ERROR: Oracle RAC on Vagrant is having problems - OL7

### ISSUE THREAD

**Issue by sivarkdbade** [oracle/vagrant-projects#507]
I am trying to setup Oracle RAC from OL7, But i'm encountering the below errors.

I copied 23 version software files into software location. But it was throwing the below error. so, placed 19c software files and but getting below errors.

c:\git\vagrant-projects\OracleRAC\OL7>vagrant up

│▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│
 Oracle RAC (Real Application Cluster) Vagrant box for KVM/libVirt or VirtualBox
 Copyright (c) 1982-2020 Oracle and/or its affiliates
----------------------------------------------------------------------------------
 Author: Ruggero Citton <ruggero.citton@oracle.com>
         RAC Pack, Cloud Innovation and Solution Engineering Team
│▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│

--------------------
Detected virtualbox
--------------------
ERROR: gi_software does not exist

==========
 node1:
    node1: Run the script on the local node first. After successful completion, you can start the script in parallel on all other nodes. After the successful root script execution, proceed to re-run the same 'gridSetup.sh -executeConfigTools' command.
    node1:
    node1: Successfully Configured Software.
    node1: -----------------------------------------------------------------
    node1: INFO: 2024-05-23 19:01:49: Make RECO DG using ASMLib
    node1: -----------------------------------------------------------------
    node1:
    node1: SQL*Plus: Release 19.0.0.0.0 - Production on Thu May 23 19:01:49 2024
    node1: Version 19.3.0.0.0
    node1:
    node1: Copyright (c) 1982, 2019, Oracle.  All rights reserved.
    node1:
    node1:
    node1: Connected to:
    node1: Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
    node1: Version 19.3.0.0.0
    node1:
    node1: SQL>   2    3    4    5    6    7    8
    node1: Diskgroup created.
    node1:
    node1: SQL> Disconnected from Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
    node1: Version 19.3.0.0.0
    node1: -----------------------------------------------------------------
    node1: INFO: 2024-05-23 19:02:13: Unzip RDBMS software
    node1: -----------------------------------------------------------------
    node1: -----------------------------------------------------------------
    node1: INFO: 2024-05-23 19:18:28: Make RDBMS software install command
    node1: -----------------------------------------------------------------
    node1: -----------------------------------------------------------------
    node1: INFO: 2024-05-23 19:18:29: RDBMS software installation
    node1: -----------------------------------------------------------------
    node1: Launching Oracle Database Setup Wizard...
    node1:
    node1: [WARNING] [INS-13013] Target environment does not meet some mandatory requirements.
    node1:    CAUSE: Some of the mandatory prerequisites are not met. See logs for details. /u01/app/oraInventory/logs/InstallActions2024-05-23_07-18-29PM/installActions2024-05-23_07-18-29PM.log
    node1:    ACTION: Identify the list of failed prerequisite checks from the log: /u01/app/oraInventory/logs/InstallActions2024-05-23_07-18-29PM/installActions2024-05-23_07-18-29PM.log. Then either from the log file or from installation manual find the appropriate configuration to meet the prerequisites and fix it manually.
    node1: The response file for this session can be found at:
    node1:  /u01/app/oracle/product/19.3.0.0/dbhome_1/install/response/db_2024-05-23_07-18-29PM.rsp
    node1:
    node1: You can find the log of this install session at:
    node1:  /u01/app/oraInventory/logs/InstallActions2024-05-23_07-18-29PM/installActions2024-05-23_07-18-29PM.log
    node1:
    node1: As a root user, execute the following script(s):
    node1:      1. /u01/app/oracle/product/19.3.0.0/dbhome_1/root.sh
    node1:
    node1: Execute /u01/app/oracle/product/19.3.0.0/dbhome_1/root.sh on the following nodes:
    node1: [node1, node2]
    node1:
    node1:
    node1: Successfully Setup Software with warning(s).
    node1: Check /u01/app/oracle/product/19.3.0.0/dbhome_1/install/root_node1_2024-05-23_19-49-02-736114700.log for the output of root script
    node1: Check /u01/app/oracle/product/19.3.0.0/dbhome_1/install/root_node2_2024-05-23_19-49-04-246013824.log for the output of root script
    node1: -----------------------------------------------------------------
    node1: INFO: 2024-05-23 19:49:04: Make create database command
    node1: -----------------------------------------------------------------
    node1: -----------------------------------------------------------------
    node1: INFO: 2024-05-23 19:49:05: Create database
    node1: -----------------------------------------------------------------
    node1: [FATAL] [DBT-14505] Oracle RAC software is not present on nodes ([node2]) selected for configuration.
    node1:    ACTION: Install Oracle RAC software on all the selected nodes before doing database configuration.
    node1: [FATAL] [DBT-14105] The specified node(s) (node2) is not configured with Oracle Grid Infrastructure.
    node1:    CAUSE: RAC database creation can only be done on nodes that are configured with Oracle Grid Infrastructure.
    node1: -----------------------------------------------------------------
    node1: INFO: 2024-05-23 19:52:03: Check database
    node1: -----------------------------------------------------------------
    node1: -----------------------------------------------------------------
    node1: INFO: 2024-05-23 19:52:04: Config database
    node1: -----------------------------------------------------------------
    node1: PRCD-1120 : The resource for database DB193H1 could not be found.
    node1: PRCR-1001 : Resource ora.db193h1.db does not exist
    node1: -----------------------------------------------------------------------------------
    node1: ERROR: 2024-05-23 19:52:09: Oracle RAC on Vagrant is having problems
    node1: -----------------------------------------------------------------------------------
    node1: -----------------------------------------------------------------
    node1: INFO: 2024-05-23 19:52:09: Running user-defined post-setup scripts
    node1: -----------------------------------------------------------------

c:\git\vagrant-projects\OracleRAC\OL7>

**Comment by sivarkdbade** [comment]
[Oracle_RAC_OL7_Log.txt](https://github.com/oracle/vagrant-projects/files/15425969/Oracle_RAC_OL7_Log.txt)

Attached full logs.

**Comment by sivarkdbade** [comment]
I have attempted to halt and start it again, but I'm facing the below issues..


```
c:\git\vagrant-projects\OracleRAC\OL7>vagrant halt

│▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│
 Oracle RAC (Real Application Cluster) Vagrant box for KVM/libVirt or VirtualBox
 Copyright (c) 1982-2020 Oracle and/or its affiliates
----------------------------------------------------------------------------------
 Author: Ruggero Citton <ruggero.citton@oracle.com>
         RAC Pack, Cloud Innovation and Solution Engineering Team
│▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│


--------------------
Detected virtualbox
--------------------
getting Proxy Configuration from Host...
==> node1: Attempting graceful shutdown of VM...
==> node1: Forcing shutdown of VM...
==> node2: Attempting graceful shutdown of VM...
==> node2: Forcing shutdown of VM...

c:\git\vagrant-projects\OracleRAC\OL7>vagrant up

│▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│
 Oracle RAC (Real Application Cluster) Vagrant box for KVM/libVirt or VirtualBox
 Copyright (c) 1982-2020 Oracle and/or its affiliates
----------------------------------------------------------------------------------
 Author: Ruggero Citton <ruggero.citton@oracle.com>
         RAC Pack, Cloud Innovation and Solution Engineering Team
│▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒│


--------------------
Detected virtualbox
--------------------
getting Proxy Configuration from Host...
Bringing machine 'node2' up with 'virtualbox' provider...
Bringing machine 'node1' up with 'virtualbox' provider...
Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.

c:\git\vagrant-projects\OracleRAC\OL7>
```

**Comment by rcitton** [comment]
Hi, could you please share config/vagrant.yml & config/setup.env

**Comment by rcitton** [comment]
Suspended, Reqd Info not Avail

**Comment by rcitton** [comment]
Suspended, Reqd Info not Avail
