### ISSUE TITLE
Please add ability to prevent update of the VBoxGuestExtensions

### ISSUE THREAD

**Issue by ToontjeM** [oracle/vagrant-projects#511]
Updating VBoxGuestExtensions takes time and is in most cases not needed. Adding the following code snippet to the Vagrantfiles gives the user the ability to prevent these time-consuming updates.
 
```
if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
end
```

Of course, the user needs to have the `vagrant-vbguest` plugin installed.

**Comment by AmedeeBulle** [comment]
Why are you using the `vagrant-vbguest` plugin if you don't want the guest additions to be updated?

**Comment by ToontjeM** [comment]
For some VM's i want, for some not. Using the plugin allows me to define this in the Vagrantfile.

**Comment by AmedeeBulle** [comment]
We assume that the majority of users who install this plugin want to get the guest additions updated.
It would be counter productive to disable it by default.

As you suggest, if one really wants to disable it, they can can add that snippet of code in their Vangrantfile.
