### ISSUE TITLE
Private network is not working with OL9 box(vbox) 9.4.625

### ISSUE THREAD

**Issue by frdeng** [oracle/vagrant-projects#528]
**Describe the issue**

After update the OL9 vbox box to 9.4.625
the private network config stops working
https://developer.hashicorp.com/vagrant/docs/networking/private_network

` c.vm.network "private_network", IP: "<IP"`

The private IP is not provisioned.

The older version 9.3.513 works fine.

**Environment (please complete the following information):**

- Host OS: OL9
- Kernel version (for Linux host): 5.15.0-208.159.3.el9uek.x86_64
- Vagrant version: vagrant-2.4.1-1.x86_64
- Vagrant provider:
  - For VirtualBox:
    - VirtualBox version: 7.0.18r162988

- Vagrant project: OL

**Additional information**

Add any other information about the issue here (console log, ...).

**Comment by frdeng** [comment]
similar issue with new OL8 box


`
==> demo-ms-0: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifdown ''
mv -f '/tmp/vagrant-network-entry--1729799956-0' '/etc/sysconfig/network-scripts/ifcfg-'
(test -f /etc/init.d/NetworkManager && /etc/init.d/NetworkManager restart) || ((systemctl | grep NetworkManager.service) && systemctl restart NetworkManager)
/sbin/ifup ''

Stdout from the command:

NetworkManager.service                                                                   loaded active running   Network Manager


Stderr from the command:

bash: line 4: /sbin/ifdown: No such file or directory
bash: line 7: /sbin/ifup: No such file or directory
`

**Comment by AmedeeBulle** [comment]
It seems that there is a regression in the metadata packaging. As workaround, add `, nic_type: "virtio"` to your private network definition stanza.

(Se #465 for more context)
